import type { AxisOneDevelopmentStage } from "@/modules/axis-1/types";

const projectId = "11111111-1111-4111-8111-111111111111";
const projectName = "GreenNest Riverside";

export const axisOneDevelopmentStages: AxisOneDevelopmentStage[] = [
  {
    id: "project-idea",
    code: "01",
    title: "Ý tưởng dự án",
    shortTitle: "Ý tưởng",
    projectId,
    projectName,
    objective:
      "Xác định cơ hội đầu tư, luận điểm phát triển và mục tiêu kinh doanh ban đầu.",
    description:
      "Ghi nhận ý tưởng dự án từ lãnh đạo hoặc bộ phận phát triển, làm rõ vị trí, quy mô sơ bộ, sản phẩm dự kiến và lý do nên tiếp tục nghiên cứu.",
    status: "completed",
    progress: 100,
    responsiblePerson: "Nguyễn Minh Anh",
    responsibleRole: "Giám đốc đầu tư",
    deadline: "2026-06-05",
    riskLevel: "low",
    requiredDocuments: [
      {
        id: "doc-idea-brief",
        name: "Phiếu ý tưởng dự án",
        owner: "Đầu tư phát triển",
        status: "approved",
      },
      {
        id: "doc-idea-location",
        name: "Bản đồ vị trí sơ bộ",
        owner: "Đầu tư phát triển",
        status: "approved",
      },
    ],
    inputData: ["Nguồn cơ hội", "Vị trí khu đất", "Quy mô sơ bộ", "Nhu cầu thị trường"],
    outputData: ["Phiếu ý tưởng", "Đề xuất nghiên cứu tiếp", "Danh mục giả định ban đầu"],
    tasks: [
      {
        id: "task-idea-1",
        title: "Chốt luận điểm đầu tư sơ bộ",
        assignee: "Nguyễn Minh Anh",
        deadline: "2026-06-05",
        status: "done",
        priority: "low",
      },
    ],
  },
  {
    id: "land-bank-dossier",
    code: "02",
    title: "Hồ sơ quỹ đất",
    shortTitle: "Quỹ đất",
    projectId,
    projectName,
    objective:
      "Chuẩn hóa dữ liệu pháp lý, hiện trạng và quyền sử dụng đất để phục vụ đánh giá phát triển dự án.",
    description:
      "Tập hợp thông tin ranh giới, hiện trạng, nguồn gốc đất, chủ sử dụng, tài sản trên đất và các vướng mắc ban đầu của quỹ đất.",
    status: "in_progress",
    progress: 72,
    responsiblePerson: "Phạm Thu Hà",
    responsibleRole: "Pháp lý dự án",
    deadline: "2026-06-18",
    riskLevel: "medium",
    requiredDocuments: [
      {
        id: "doc-land-title",
        name: "Giấy chứng nhận quyền sử dụng đất",
        owner: "Pháp lý",
        status: "submitted",
      },
      {
        id: "doc-land-boundary",
        name: "Bản vẽ ranh giới khu đất",
        owner: "Kỹ thuật",
        status: "approved",
      },
      {
        id: "doc-land-current",
        name: "Biên bản khảo sát hiện trạng",
        owner: "Đầu tư phát triển",
        status: "missing",
        dueDate: "2026-06-14",
        note: "Cần bổ sung ảnh hiện trạng và xác nhận mốc giới.",
      },
    ],
    inputData: ["Hồ sơ đất", "Ranh giới", "Hiện trạng sử dụng", "Thông tin chủ đất"],
    outputData: ["Bộ hồ sơ quỹ đất", "Danh sách vướng mắc đất đai", "Bản đồ hiện trạng"],
    tasks: [
      {
        id: "task-land-1",
        title: "Bổ sung biên bản khảo sát hiện trạng",
        assignee: "Lâm Đầu Tư",
        deadline: "2026-06-14",
        status: "in_progress",
        priority: "medium",
      },
      {
        id: "task-land-2",
        title: "Đối chiếu ranh giới với hồ sơ địa chính",
        assignee: "Phạm Thu Hà",
        deadline: "2026-06-18",
        status: "open",
        priority: "medium",
      },
    ],
  },
  {
    id: "planning-check",
    code: "03",
    title: "Kiểm tra quy hoạch",
    shortTitle: "Quy hoạch",
    projectId,
    projectName,
    objective:
      "Xác định khu đất có phù hợp quy hoạch và chỉ tiêu phát triển dự kiến hay không.",
    description:
      "Rà soát quy hoạch phân khu, quy hoạch chung, chức năng sử dụng đất, chỉ tiêu dân số, tầng cao, mật độ và các hạn chế kỹ thuật.",
    status: "blocked",
    progress: 45,
    responsiblePerson: "Bùi Minh Khoa",
    responsibleRole: "Kỹ thuật quy hoạch",
    deadline: "2026-06-25",
    riskLevel: "high",
    requiredDocuments: [
      {
        id: "doc-planning-map",
        name: "Trích lục quy hoạch",
        owner: "Quy hoạch",
        status: "submitted",
      },
      {
        id: "doc-planning-index",
        name: "Bảng chỉ tiêu quy hoạch sơ bộ",
        owner: "Kỹ thuật",
        status: "draft",
      },
      {
        id: "doc-planning-authority",
        name: "Văn bản xác nhận thông tin quy hoạch",
        owner: "Pháp lý",
        status: "missing",
        dueDate: "2026-06-20",
      },
    ],
    inputData: ["Quy hoạch phân khu", "Ranh đất", "Chỉ tiêu mục tiêu", "Yêu cầu sản phẩm"],
    outputData: ["Báo cáo kiểm tra quy hoạch", "Danh sách chỉ tiêu rủi ro", "Khuyến nghị tiếp tục/dừng"],
    tasks: [
      {
        id: "task-planning-1",
        title: "Làm rõ chỉ tiêu dân số với cơ quan quản lý",
        assignee: "Bùi Minh Khoa",
        deadline: "2026-06-20",
        status: "blocked",
        priority: "high",
      },
    ],
  },
  {
    id: "social-housing-conditions",
    code: "04",
    title: "Điều kiện phát triển NƠXH",
    shortTitle: "NƠXH",
    projectId,
    projectName,
    objective:
      "Đánh giá nghĩa vụ, điều kiện và khả năng phát triển nhà ở xã hội trong cấu trúc dự án.",
    description:
      "Kiểm tra tỷ lệ quỹ đất, đối tượng áp dụng, cơ chế ưu đãi, yêu cầu pháp lý và tác động tài chính nếu dự án có cấu phần NƠXH.",
    status: "waiting_review",
    progress: 60,
    responsiblePerson: "Trần Hoàng Nam",
    responsibleRole: "Phó Tổng giám đốc",
    deadline: "2026-06-28",
    riskLevel: "medium",
    requiredDocuments: [
      {
        id: "doc-noxh-policy",
        name: "Bảng rà soát chính sách NƠXH",
        owner: "Pháp lý",
        status: "submitted",
      },
      {
        id: "doc-noxh-finance",
        name: "Ước tính tác động tài chính NƠXH",
        owner: "Tài chính",
        status: "draft",
      },
    ],
    inputData: ["Quy mô đất ở", "Chỉ tiêu quy hoạch", "Chính sách địa phương", "Cơ cấu sản phẩm"],
    outputData: ["Kết luận điều kiện NƠXH", "Phương án nghĩa vụ NƠXH", "Khuyến nghị lãnh đạo"],
    tasks: [
      {
        id: "task-noxh-1",
        title: "Rà soát ưu đãi và nghĩa vụ NƠXH",
        assignee: "Phạm Thu Hà",
        deadline: "2026-06-24",
        status: "in_progress",
        priority: "medium",
      },
    ],
  },
  {
    id: "pre-feasibility-analysis",
    code: "05",
    title: "Phân tích tiền khả thi",
    shortTitle: "Tiền khả thi",
    projectId,
    projectName,
    objective:
      "Đánh giá nhanh hiệu quả đầu tư, khả năng triển khai và các rủi ro chính trước khi trình chủ trương.",
    description:
      "Tổng hợp dữ liệu thị trường, chi phí, doanh thu, tiến độ, pháp lý và kỹ thuật để xác định mức hấp dẫn đầu tư.",
    status: "in_progress",
    progress: 68,
    responsiblePerson: "Đinh Tài Chính",
    responsibleRole: "Quản lý tài chính",
    deadline: "2026-07-02",
    riskLevel: "medium",
    requiredDocuments: [
      {
        id: "doc-prefeas-model",
        name: "Mô hình tài chính tiền khả thi",
        owner: "Tài chính",
        status: "draft",
      },
      {
        id: "doc-prefeas-market",
        name: "Báo cáo thị trường sơ bộ",
        owner: "Đầu tư phát triển",
        status: "submitted",
      },
      {
        id: "doc-prefeas-risk",
        name: "Ma trận rủi ro tiền khả thi",
        owner: "PMO",
        status: "missing",
        dueDate: "2026-06-30",
      },
    ],
    inputData: ["Giá bán tham chiếu", "Tổng mức đầu tư sơ bộ", "Tiến độ dự kiến", "Rủi ro pháp lý"],
    outputData: ["Báo cáo tiền khả thi", "Mô hình IRR/NPV sơ bộ", "Khuyến nghị đầu tư"],
    tasks: [
      {
        id: "task-prefeas-1",
        title: "Hoàn thiện ma trận rủi ro tiền khả thi",
        assignee: "Hoàng Gia Khánh",
        deadline: "2026-06-30",
        status: "open",
        priority: "medium",
      },
    ],
  },
  {
    id: "investor-capacity-dossier",
    code: "06",
    title: "Hồ sơ năng lực chủ đầu tư",
    shortTitle: "Năng lực CĐT",
    projectId,
    projectName,
    objective:
      "Chuẩn bị hồ sơ chứng minh năng lực tài chính, kinh nghiệm và pháp nhân chủ đầu tư.",
    description:
      "Tập hợp hồ sơ pháp nhân, báo cáo tài chính, kinh nghiệm phát triển dự án, cam kết vốn và tài liệu chứng minh năng lực triển khai.",
    status: "in_progress",
    progress: 55,
    responsiblePerson: "Nguyễn Minh Anh",
    responsibleRole: "Admin dự án",
    deadline: "2026-07-08",
    riskLevel: "medium",
    requiredDocuments: [
      {
        id: "doc-capacity-business",
        name: "Đăng ký doanh nghiệp và điều lệ",
        owner: "Pháp chế công ty",
        status: "approved",
      },
      {
        id: "doc-capacity-finance",
        name: "Báo cáo tài chính kiểm toán",
        owner: "Tài chính",
        status: "submitted",
      },
      {
        id: "doc-capacity-experience",
        name: "Danh mục dự án đã triển khai",
        owner: "Đầu tư phát triển",
        status: "missing",
        dueDate: "2026-07-03",
      },
    ],
    inputData: ["Hồ sơ pháp nhân", "Báo cáo tài chính", "Kinh nghiệm dự án", "Cam kết nguồn vốn"],
    outputData: ["Bộ hồ sơ năng lực", "Bảng kiểm năng lực", "Gói tài liệu trình cơ quan"],
    tasks: [
      {
        id: "task-capacity-1",
        title: "Cập nhật danh mục dự án đã triển khai",
        assignee: "Lâm Đầu Tư",
        deadline: "2026-07-03",
        status: "open",
        priority: "medium",
      },
    ],
  },
  {
    id: "investment-policy-approval",
    code: "07",
    title: "Chấp thuận chủ trương đầu tư",
    shortTitle: "Chủ trương ĐT",
    projectId,
    projectName,
    objective:
      "Theo dõi hồ sơ, trạng thái nộp và phản hồi liên quan đến chấp thuận chủ trương đầu tư.",
    description:
      "Quản lý bộ hồ sơ trình chủ trương đầu tư, công văn, yêu cầu bổ sung, lịch làm việc và trạng thái xử lý với cơ quan có thẩm quyền.",
    status: "not_started",
    progress: 20,
    responsiblePerson: "Phạm Thu Hà",
    responsibleRole: "Pháp lý dự án",
    deadline: "2026-07-22",
    riskLevel: "high",
    requiredDocuments: [
      {
        id: "doc-policy-proposal",
        name: "Tờ trình chấp thuận chủ trương đầu tư",
        owner: "Pháp lý",
        status: "draft",
      },
      {
        id: "doc-policy-dossier",
        name: "Bộ hồ sơ đề xuất dự án",
        owner: "Đầu tư phát triển",
        status: "missing",
        dueDate: "2026-07-12",
      },
    ],
    inputData: ["Báo cáo tiền khả thi", "Hồ sơ quỹ đất", "Hồ sơ năng lực", "Văn bản pháp lý liên quan"],
    outputData: ["Hồ sơ nộp chủ trương", "Theo dõi phản hồi", "Quyết định/chấp thuận chủ trương"],
    tasks: [
      {
        id: "task-policy-1",
        title: "Lập danh mục hồ sơ nộp chủ trương",
        assignee: "Phạm Thu Hà",
        deadline: "2026-07-12",
        status: "open",
        priority: "high",
      },
    ],
  },
  {
    id: "detailed-planning-1-500",
    code: "08",
    title: "Quy hoạch chi tiết 1/500",
    shortTitle: "QH 1/500",
    projectId,
    projectName,
    objective:
      "Quản lý quy trình lập, rà soát và phê duyệt quy hoạch chi tiết tỷ lệ 1/500.",
    description:
      "Theo dõi nhiệm vụ quy hoạch, phương án tổng mặt bằng, chỉ tiêu kỹ thuật, bản vẽ, lấy ý kiến và hồ sơ trình phê duyệt 1/500.",
    status: "not_started",
    progress: 12,
    responsiblePerson: "Bùi Minh Khoa",
    responsibleRole: "Kỹ thuật quy hoạch",
    deadline: "2026-08-15",
    riskLevel: "high",
    requiredDocuments: [
      {
        id: "doc-1500-task",
        name: "Nhiệm vụ quy hoạch 1/500",
        owner: "Quy hoạch",
        status: "missing",
        dueDate: "2026-07-25",
      },
      {
        id: "doc-1500-drawing",
        name: "Bộ bản vẽ quy hoạch 1/500",
        owner: "Thiết kế",
        status: "missing",
        dueDate: "2026-08-05",
      },
    ],
    inputData: ["Chủ trương đầu tư", "Chỉ tiêu quy hoạch", "Khảo sát hiện trạng", "Yêu cầu sản phẩm"],
    outputData: ["Nhiệm vụ quy hoạch", "Bộ bản vẽ 1/500", "Hồ sơ trình phê duyệt 1/500"],
    tasks: [
      {
        id: "task-1500-1",
        title: "Chuẩn bị nhiệm vụ quy hoạch 1/500",
        assignee: "Bùi Minh Khoa",
        deadline: "2026-07-25",
        status: "open",
        priority: "high",
      },
    ],
  },
  {
    id: "basic-design",
    code: "09",
    title: "Thiết kế cơ sở",
    shortTitle: "Thiết kế cơ sở",
    projectId,
    projectName,
    objective:
      "Lập thiết kế cơ sở đáp ứng quy hoạch, công năng, kỹ thuật và tiền đề cho báo cáo khả thi.",
    description:
      "Quản lý hồ sơ thiết kế cơ sở gồm kiến trúc, kết cấu, MEP, chỉ tiêu kỹ thuật, phối hợp BIM và phản hồi nội bộ.",
    status: "not_started",
    progress: 8,
    responsiblePerson: "Đỗ Hải Yến",
    responsibleRole: "Thiết kế",
    deadline: "2026-08-30",
    riskLevel: "medium",
    requiredDocuments: [
      {
        id: "doc-basic-arch",
        name: "Thuyết minh thiết kế cơ sở",
        owner: "Thiết kế",
        status: "missing",
        dueDate: "2026-08-20",
      },
      {
        id: "doc-basic-mep",
        name: "Hồ sơ MEP sơ bộ",
        owner: "Kỹ thuật",
        status: "missing",
        dueDate: "2026-08-24",
      },
    ],
    inputData: ["Quy hoạch 1/500", "Nhiệm vụ thiết kế", "Suất đầu tư", "Tiêu chuẩn kỹ thuật"],
    outputData: ["Thiết kế cơ sở", "Bảng chỉ tiêu kỹ thuật", "Danh mục vấn đề thiết kế"],
    tasks: [
      {
        id: "task-basic-1",
        title: "Thiết lập cấu trúc hồ sơ thiết kế cơ sở",
        assignee: "Đỗ Hải Yến",
        deadline: "2026-08-20",
        status: "open",
        priority: "medium",
      },
    ],
  },
  {
    id: "feasibility-study-report",
    code: "10",
    title: "Báo cáo nghiên cứu khả thi",
    shortTitle: "Báo cáo khả thi",
    projectId,
    projectName,
    objective:
      "Tổng hợp cơ sở pháp lý, kỹ thuật, tài chính và hiệu quả đầu tư để trình phê duyệt dự án.",
    description:
      "Quản lý phần nội dung FS gồm tổng mức đầu tư, hiệu quả tài chính, phương án thiết kế, tiến độ, môi trường, PCCC và rủi ro triển khai.",
    status: "not_started",
    progress: 5,
    responsiblePerson: "Hoàng Gia Khánh",
    responsibleRole: "Giám đốc dự án",
    deadline: "2026-09-18",
    riskLevel: "medium",
    requiredDocuments: [
      {
        id: "doc-fs-main",
        name: "Báo cáo nghiên cứu khả thi",
        owner: "PMO",
        status: "missing",
        dueDate: "2026-09-10",
      },
      {
        id: "doc-fs-cost",
        name: "Tổng mức đầu tư",
        owner: "Tài chính",
        status: "missing",
        dueDate: "2026-09-05",
      },
    ],
    inputData: ["Thiết kế cơ sở", "Tổng mức đầu tư", "Pháp lý dự án", "Phương án tiến độ"],
    outputData: ["Báo cáo FS", "Hồ sơ trình thẩm định", "Danh mục điều kiện phê duyệt"],
    tasks: [
      {
        id: "task-fs-1",
        title: "Mở khung báo cáo nghiên cứu khả thi",
        assignee: "Hoàng Gia Khánh",
        deadline: "2026-09-10",
        status: "open",
        priority: "medium",
      },
    ],
  },
  {
    id: "investor-approval",
    code: "11",
    title: "Chấp thuận chủ đầu tư",
    shortTitle: "Chủ đầu tư",
    projectId,
    projectName,
    objective:
      "Theo dõi điều kiện, hồ sơ và quyết định chấp thuận/chỉ định chủ đầu tư.",
    description:
      "Quản lý hồ sơ đề nghị chấp thuận chủ đầu tư, năng lực, nghĩa vụ tài chính, phản hồi cơ quan và quyết định cuối cùng.",
    status: "not_started",
    progress: 0,
    responsiblePerson: "Phạm Thu Hà",
    responsibleRole: "Pháp lý dự án",
    deadline: "2026-10-05",
    riskLevel: "medium",
    requiredDocuments: [
      {
        id: "doc-investor-request",
        name: "Đơn đề nghị chấp thuận chủ đầu tư",
        owner: "Pháp lý",
        status: "missing",
        dueDate: "2026-09-26",
      },
      {
        id: "doc-investor-capacity",
        name: "Hồ sơ năng lực cập nhật",
        owner: "Đầu tư phát triển",
        status: "missing",
        dueDate: "2026-09-28",
      },
    ],
    inputData: ["Chủ trương đầu tư", "Hồ sơ năng lực", "Nghĩa vụ tài chính", "Hồ sơ pháp lý"],
    outputData: ["Hồ sơ chấp thuận chủ đầu tư", "Quyết định/chấp thuận chủ đầu tư"],
    tasks: [
      {
        id: "task-investor-1",
        title: "Lập checklist điều kiện chấp thuận chủ đầu tư",
        assignee: "Phạm Thu Hà",
        deadline: "2026-09-26",
        status: "open",
        priority: "medium",
      },
    ],
  },
  {
    id: "land-allocation-lease",
    code: "12",
    title: "Giao đất / cho thuê đất",
    shortTitle: "Giao/thuê đất",
    projectId,
    projectName,
    objective:
      "Theo dõi thủ tục giao đất, cho thuê đất, chuyển mục đích và hoàn thành nghĩa vụ liên quan.",
    description:
      "Quản lý hồ sơ đất đai sau chấp thuận chủ đầu tư, bao gồm quyết định giao/thuê đất, nghĩa vụ tài chính, hợp đồng thuê đất và bàn giao mốc giới.",
    status: "not_started",
    progress: 0,
    responsiblePerson: "Phạm Thu Hà",
    responsibleRole: "Pháp lý dự án",
    deadline: "2026-11-15",
    riskLevel: "critical",
    requiredDocuments: [
      {
        id: "doc-land-allocation-request",
        name: "Hồ sơ đề nghị giao đất/cho thuê đất",
        owner: "Pháp lý",
        status: "missing",
        dueDate: "2026-10-20",
      },
      {
        id: "doc-land-financial",
        name: "Thông báo nghĩa vụ tài chính đất đai",
        owner: "Tài chính",
        status: "missing",
        dueDate: "2026-11-01",
      },
      {
        id: "doc-land-handover",
        name: "Biên bản bàn giao đất ngoài thực địa",
        owner: "Pháp lý",
        status: "missing",
        dueDate: "2026-11-15",
      },
    ],
    inputData: ["Chấp thuận chủ đầu tư", "Hồ sơ đất", "Nghĩa vụ tài chính", "Ranh giới bàn giao"],
    outputData: ["Quyết định giao/thuê đất", "Hợp đồng thuê đất", "Biên bản bàn giao mốc giới"],
    tasks: [
      {
        id: "task-land-lease-1",
        title: "Lập kế hoạch thủ tục giao/thuê đất",
        assignee: "Phạm Thu Hà",
        deadline: "2026-10-20",
        status: "open",
        priority: "critical",
      },
    ],
  },
];
