import type { Role } from "@/constants/roles";

export const PERMISSIONS = [
  "project.view",
  "project.create",
  "project.update",
  "project.archive",
  "project.assign_member",
  "task.view",
  "task.create",
  "task.update",
  "task.update_own",
  "task.archive",
  "document.view",
  "document.create",
  "document.update",
  "document.approve",
  "document.archive",
  "legal.view",
  "legal.update",
  "legal.approve",
  "legal.configure_template",
  "meeting.view",
  "meeting.create",
  "meeting.update",
  "decision.create",
  "decision.approve",
  "knowledge.view",
  "knowledge.create",
  "knowledge.create_candidate",
  "knowledge.promote",
  "knowledge.review",
  "knowledge.approve",
  "knowledge.manage_source_registry",
  "report.view",
  "report.create",
  "design.view",
  "design.create",
  "design.update",
  "design.review",
  "design.approve_change",
  "construction.view",
  "construction.update",
  "site_diary.create",
  "quality.update",
  "acceptance.approve",
  "finance.view",
  "finance.create",
  "finance.update",
  "finance.approve",
  "payment.request",
  "payment.approve",
  "proposal.view",
  "proposal.create",
  "proposal.update",
  "proposal.review",
  "proposal.approve",
  "proposal.reject",
  "proposal.request_change",
  "proposal.configure_flow",
  "proposal.archive",
  "investment.view",
  "investment.create",
  "investment.update",
  "investment.review",
  "investment.approve",
  "contract.view",
  "contract.create",
  "contract.update",
  "contract.review",
  "contract.approve",
  "contract.archive",
  "hr.view",
  "hr.create",
  "hr.update",
  "hr.review",
  "hr.approve",
  "qa.view",
  "qa.update",
  "qa.approve",
  "safety.view",
  "safety.update",
  "safety.approve",
  "compliance.view",
  "compliance.review",
  "internal_audit.view",
  "internal_audit.review",
  "user.view",
  "user.invite",
  "user.update_role",
  "settings.manage",
  "audit.view",
  "ai.use",
  "ai.ask",
  "ai.use_rag",
  "ai.view_insight",
  "ai.create_draft",
  "ai.propose_action",
  "ai.confirm_action",
  "ai.configure"
] as const;

export type PermissionAction = (typeof PERMISSIONS)[number];

export type PermissionUser = {
  id: string;
  role: Role;
  permissions?: PermissionAction[];
};

export type PermissionResource = {
  id?: string;
  projectId?: string;
  assigneeId?: string;
  ownerId?: string;
};

const allPermissions = [...PERMISSIONS];

function resolveEffectivePermissions(permissions: PermissionAction[]) {
  const effectivePermissions = new Set(permissions);

  if (effectivePermissions.has("knowledge.create")) {
    effectivePermissions.add("knowledge.create_candidate");
  }

  if (effectivePermissions.has("knowledge.review")) {
    effectivePermissions.add("knowledge.promote");
  }

  if (effectivePermissions.has("settings.manage")) {
    effectivePermissions.add("knowledge.manage_source_registry");
    effectivePermissions.add("ai.configure");
  }

  if (effectivePermissions.has("ai.use")) {
    effectivePermissions.add("ai.ask");
  }

  if (effectivePermissions.has("ai.view_insight")) {
    effectivePermissions.add("ai.use_rag");
    effectivePermissions.add("ai.create_draft");
  }

  if (effectivePermissions.has("ai.confirm_action")) {
    effectivePermissions.add("ai.propose_action");
  }

  return [...effectivePermissions];
}

const portfolioReadPermissions = [
  "project.view",
  "task.view",
  "document.view",
  "legal.view",
  "meeting.view",
  "knowledge.view",
  "report.view",
  "design.view",
  "construction.view",
  "finance.view",
  "proposal.view",
  "investment.view",
  "contract.view",
  "hr.view",
  "qa.view",
  "safety.view",
  "compliance.view",
  "internal_audit.view",
  "audit.view",
  "ai.use",
  "ai.view_insight"
] satisfies PermissionAction[];

export const ROLE_PERMISSIONS: Record<Role, PermissionAction[]> = {
  super_admin: allPermissions,
  admin: allPermissions.filter((permission) => !["finance.create", "finance.update", "finance.approve", "payment.approve"].includes(permission)),
  tong_giam_doc: [
    "project.view",
    "project.create",
    "project.update",
    "project.archive",
    "project.assign_member",
    "task.view",
    "task.create",
    "task.update",
    "task.archive",
    "document.view",
    "legal.view",
    "legal.approve",
    "meeting.view",
    "meeting.create",
    "meeting.update",
    "decision.create",
    "decision.approve",
    "knowledge.view",
    "knowledge.create",
    "knowledge.review",
    "knowledge.approve",
    "report.view",
    "report.create",
    "design.view",
    "construction.view",
    "finance.view",
    "finance.approve",
    "payment.approve",
    "user.view",
    "audit.view",
    "ai.use",
    "ai.view_insight",
    "ai.confirm_action"
  ],
  pho_tong_giam_doc: [
    "project.view",
    "project.create",
    "project.update",
    "task.view",
    "task.create",
    "task.update",
    "task.archive",
    "document.view",
    "legal.view",
    "legal.approve",
    "meeting.view",
    "meeting.create",
    "meeting.update",
    "decision.create",
    "decision.approve",
    "knowledge.view",
    "knowledge.create",
    "knowledge.review",
    "knowledge.approve",
    "report.view",
    "report.create",
    "design.view",
    "construction.view",
    "finance.view",
    "audit.view",
    "ai.use",
    "ai.view_insight",
    "ai.confirm_action"
  ],
  giam_doc_du_an: [
    "project.view",
    "project.create",
    "project.update",
    "project.archive",
    "project.assign_member",
    "task.view",
    "task.create",
    "task.update",
    "task.archive",
    "document.view",
    "document.create",
    "document.update",
    "document.archive",
    "legal.view",
    "legal.update",
    "meeting.view",
    "meeting.create",
    "meeting.update",
    "decision.create",
    "knowledge.view",
    "knowledge.create",
    "knowledge.review",
    "knowledge.approve",
    "report.view",
    "report.create",
    "design.view",
    "design.create",
    "design.update",
    "construction.view",
    "construction.update",
    "finance.view",
    "audit.view",
    "ai.use",
    "ai.view_insight",
    "ai.confirm_action"
  ],
  quan_ly_du_an: [
    "project.view",
    "project.create",
    "project.update",
    "task.view",
    "task.create",
    "task.update",
    "document.view",
    "document.create",
    "document.update",
    "legal.view",
    "legal.update",
    "meeting.view",
    "meeting.create",
    "meeting.update",
    "decision.create",
    "knowledge.view",
    "knowledge.create",
    "knowledge.review",
    "knowledge.approve",
    "report.view",
    "report.create",
    "design.view",
    "design.create",
    "design.update",
    "construction.view",
    "construction.update",
    "finance.view",
    "audit.view",
    "ai.use",
    "ai.view_insight"
  ],
  to_truong: [
    "project.view",
    "task.view",
    "task.create",
    "task.update_own",
    "document.view",
    "meeting.view",
    "knowledge.view",
    "report.view",
    "design.view",
    "construction.view",
    "construction.update",
    "site_diary.create",
    "quality.update",
    "ai.use"
  ],
  phap_ly: [
    "project.view",
    "task.view",
    "task.create",
    "task.update_own",
    "document.view",
    "document.create",
    "document.update",
    "legal.view",
    "legal.update",
    "legal.approve",
    "meeting.view",
    "meeting.create",
    "knowledge.view",
    "knowledge.create",
    "knowledge.review",
    "knowledge.approve",
    "report.view",
    "ai.use",
    "ai.view_insight"
  ],
  ke_toan: [
    "project.view",
    "task.view",
    "task.create",
    "task.update_own",
    "document.view",
    "finance.view",
    "finance.create",
    "finance.update",
    "finance.approve",
    "payment.request",
    "payment.approve",
    "audit.view",
    "knowledge.view",
    "knowledge.create",
    "knowledge.review",
    "knowledge.approve",
    "report.view",
    "ai.use",
    "ai.view_insight"
  ],
  thiet_ke: [
    "project.view",
    "task.view",
    "task.create",
    "task.update_own",
    "document.view",
    "document.create",
    "document.update",
    "legal.view",
    "meeting.view",
    "knowledge.view",
    "knowledge.create",
    "knowledge.review",
    "knowledge.approve",
    "design.view",
    "design.create",
    "design.update",
    "design.review",
    "design.approve_change",
    "audit.view",
    "report.view",
    "ai.use",
    "ai.view_insight"
  ],
  ky_thuat: [
    "project.view",
    "task.view",
    "task.create",
    "task.update_own",
    "document.view",
    "document.create",
    "document.update",
    "legal.view",
    "meeting.view",
    "knowledge.view",
    "knowledge.create",
    "knowledge.review",
    "design.view",
    "design.update",
    "construction.view",
    "quality.update",
    "audit.view",
    "report.view",
    "ai.use"
  ],
  thi_cong: [
    "project.view",
    "task.view",
    "task.create",
    "task.update_own",
    "document.view",
    "document.create",
    "document.update",
    "meeting.view",
    "knowledge.view",
    "knowledge.create",
    "knowledge.review",
    "design.view",
    "construction.view",
    "construction.update",
    "site_diary.create",
    "quality.update",
    "audit.view",
    "report.view",
    "ai.use"
  ],
  mua_hang: [
    "project.view",
    "task.view",
    "task.create",
    "task.update_own",
    "document.view",
    "document.create",
    "document.update",
    "meeting.view",
    "knowledge.view",
    "knowledge.create",
    "knowledge.review",
    "construction.view",
    "finance.view",
    "audit.view",
    "report.view",
    "ai.use"
  ],
  dau_tu_phat_trien: [
    "project.view",
    "document.view",
    "task.view",
    "meeting.view",
    "knowledge.view",
    "report.view",
    "proposal.view",
    "proposal.create",
    "proposal.update",
    "proposal.review",
    "investment.view",
    "investment.create",
    "investment.update",
    "investment.review",
    "finance.view",
    "contract.view",
    "ai.use",
    "ai.view_insight"
  ],
  quan_ly_tai_chinh: [
    "project.view",
    "task.view",
    "document.view",
    "meeting.view",
    "knowledge.view",
    "report.view",
    "proposal.view",
    "proposal.create",
    "proposal.update",
    "proposal.review",
    "proposal.approve",
    "proposal.reject",
    "proposal.request_change",
    "finance.view",
    "finance.create",
    "finance.update",
    "finance.approve",
    "payment.request",
    "payment.approve",
    "investment.view",
    "contract.view",
    "contract.review",
    "audit.view",
    "ai.use",
    "ai.view_insight",
    "ai.confirm_action"
  ],
  hanh_chinh_nhan_su: [
    "task.view",
    "task.create",
    "task.update_own",
    "document.view",
    "document.create",
    "knowledge.view",
    "report.view",
    "proposal.view",
    "proposal.create",
    "proposal.update",
    "proposal.review",
    "hr.view",
    "hr.create",
    "hr.update",
    "hr.review",
    "ai.use",
    "ai.view_insight"
  ],
  qa_qc_chat_luong: [
    "project.view",
    "task.view",
    "task.create",
    "task.update_own",
    "document.view",
    "document.create",
    "construction.view",
    "quality.update",
    "acceptance.approve",
    "proposal.view",
    "proposal.create",
    "proposal.review",
    "qa.view",
    "qa.update",
    "qa.approve",
    "safety.view",
    "knowledge.view",
    "report.view",
    "ai.use",
    "ai.view_insight"
  ],
  an_toan_lao_dong: [
    "project.view",
    "task.view",
    "task.create",
    "task.update_own",
    "document.view",
    "document.create",
    "construction.view",
    "proposal.view",
    "proposal.create",
    "proposal.review",
    "qa.view",
    "safety.view",
    "safety.update",
    "safety.approve",
    "knowledge.view",
    "report.view",
    "ai.use",
    "ai.view_insight"
  ],
  kiem_toan_noi_bo: [
    "project.view",
    "task.view",
    "document.view",
    "legal.view",
    "meeting.view",
    "knowledge.view",
    "report.view",
    "design.view",
    "construction.view",
    "finance.view",
    "contract.view",
    "proposal.view",
    "proposal.review",
    "audit.view",
    "compliance.view",
    "compliance.review",
    "internal_audit.view",
    "internal_audit.review",
    "ai.use",
    "ai.view_insight"
  ],
  quan_ly_hop_dong: [
    "project.view",
    "task.view",
    "task.create",
    "task.update_own",
    "document.view",
    "document.create",
    "document.update",
    "meeting.view",
    "knowledge.view",
    "report.view",
    "proposal.view",
    "proposal.create",
    "proposal.update",
    "proposal.review",
    "proposal.approve",
    "contract.view",
    "contract.create",
    "contract.update",
    "contract.review",
    "contract.approve",
    "contract.archive",
    "finance.view",
    "payment.request",
    "audit.view",
    "ai.use",
    "ai.view_insight"
  ],
  thu_ky_tro_ly: [
    "project.view",
    "task.view",
    "task.create",
    "task.update",
    "document.view",
    "document.create",
    "document.update",
    "legal.view",
    "legal.update",
    "meeting.view",
    "meeting.create",
    "meeting.update",
    "decision.create",
    "knowledge.view",
    "knowledge.create",
    "report.view",
    "report.create",
    "design.view",
    "construction.view",
    "ai.use",
    "ai.view_insight"
  ],
  kiem_soat_noi_bo: [...portfolioReadPermissions],
  nha_thau: [
    "project.view",
    "task.view",
    "task.update_own",
    "document.view",
    "document.create",
    "meeting.view",
    "knowledge.view",
    "report.view",
    "design.view",
    "construction.view",
    "construction.update",
    "site_diary.create"
  ],
  tu_van: [
    "project.view",
    "task.view",
    "task.update_own",
    "document.view",
    "document.create",
    "document.update",
    "legal.view",
    "meeting.view",
    "knowledge.view",
    "report.view",
    "design.view",
    "design.review"
  ],
  viewer: [
    "project.view",
    "task.view",
    "document.view",
    "legal.view",
    "meeting.view",
    "knowledge.view",
    "report.view",
    "design.view",
    "construction.view",
    "finance.view"
  ]
};

export function getRolePermissions(role: Role) {
  return resolveEffectivePermissions(ROLE_PERMISSIONS[role]);
}

export function can(userOrRole: PermissionUser | Role, action: PermissionAction, resource?: PermissionResource) {
  const user = typeof userOrRole === "string" ? { id: "", role: userOrRole } : userOrRole;
  const permissions = new Set(resolveEffectivePermissions([...(ROLE_PERMISSIONS[user.role] ?? []), ...(user.permissions ?? [])]));

  if (permissions.has(action)) {
    return true;
  }

  if (action === "task.update" && permissions.has("task.update_own")) {
    return Boolean(resource && user.id && (resource.assigneeId === user.id || resource.ownerId === user.id));
  }

  return false;
}

export function assertCan(user: PermissionUser, action: PermissionAction, resource?: PermissionResource) {
  if (!can(user, action, resource)) {
    throw new Error("Bạn không có quyền thực hiện thao tác này.");
  }
}
