import type {
  AuthorityMatrixRow,
  ExecutiveAuditLogItem,
  ExecutiveAiLeadershipSummary,
  ExecutiveAiInsight,
  ExecutiveAxisDefinition,
  ExecutiveCommandCenterSnapshot,
  ExecutiveDashboardLayer,
  ExecutiveDecisionLogItem,
  ExecutiveDirective,
  ExecutiveEscalationRule,
  ExecutiveGlobalStatusItem,
  ExecutiveLeadershipActionItem,
  ExecutiveLeader,
  ExecutiveNotification,
  ExecutiveOrganization,
  ExecutiveOverviewCard,
  ExecutiveProgressSegment,
  ExecutiveProjectRow,
  ExecutiveQuickAction,
  ExecutiveRoleDefinition,
  ExecutiveScheduleItem,
  ExecutiveScopeRule,
  ExecutiveUrgentItem,
  ExecutiveWorkspaceSwitchItem,
  LeadershipApproval,
  LeadershipMeeting,
  StrategicInvestmentPlan,
} from "@/modules/executive/types";

export const organizations: ExecutiveOrganization[] = [
  {
    id: "org-green-nest",
    name: "Green Nest Group",
    code: "GNG",
    type: "internal",
    isolationLabel: "Du lieu noi bo Green Nest",
  },
  {
    id: "org-horizon",
    name: "Horizon Urban Partner",
    code: "HUP",
    type: "managed_external",
    isolationLabel: "Du lieu quan ly thue, tach biet voi Green Nest",
  },
];

export const executiveRoleDefinitions: ExecutiveRoleDefinition[] = [
  {
    role: "CHAIRMAN",
    label: "Chairman / Chủ tịch",
    hierarchyLevel: 500,
    scope: "Toàn công ty, toàn hệ sinh thái, toàn bộ dự án được cấp quyền.",
    manages: [
      "KPI tổng",
      "Dòng tiền tổng",
      "Rủi ro đỏ",
      "Dự án cảnh báo đỏ",
      "Quyết định chiến lược",
      "Vấn đề vượt ngưỡng",
    ],
    doesNotHandle: [
      "Chuyên môn sâu",
      "Tác vụ hằng ngày",
      "Khoản chi nhỏ",
      "Bản vẽ hoặc hồ sơ kỹ thuật chi tiết",
    ],
    dashboardLayers: ["global"],
    decisionVisibility: {
      approvalLevels: ["CHAIRMAN"],
      riskLevels: ["critical"],
      projectImportances: ["strategic"],
      includeLegalImpact: true,
      includeScheduleImpact: false,
      includeTodayDecisions: true,
    },
  },
  {
    role: "CEO",
    label: "CEO / Tổng giám đốc",
    hierarchyLevel: 400,
    scope: "Toàn bộ dự án thuộc công ty và toàn bộ 3 trục được cấp quyền.",
    manages: [
      "Điều hành tổng thể",
      "Tiến độ tổng",
      "Dòng tiền",
      "Điều phối giữa các trục",
      "KPI hệ thống",
      "Rủi ro vận hành",
    ],
    doesNotHandle: ["Tác vụ nhân viên", "Checklist chuyên môn chi tiết"],
    dashboardLayers: ["global", "project", "department"],
    decisionVisibility: {
      approvalLevels: ["PROJECT_DIRECTOR", "CEO", "CHAIRMAN"],
      riskLevels: ["high", "critical"],
      projectImportances: ["important", "strategic"],
      includeLegalImpact: true,
      includeScheduleImpact: true,
      includeTodayDecisions: true,
    },
  },
  {
    role: "PROJECT_DIRECTOR",
    label: "Project Director / Giám đốc dự án",
    hierarchyLevel: 300,
    scope: "Một hoặc nhiều dự án được giao, quản lý cả 3 trục trong phạm vi dự án.",
    manages: [
      "Tiến độ dự án",
      "Hồ sơ dự án",
      "Thi công",
      "Chi phí",
      "Nhà thầu",
      "Trình duyệt cấp dự án",
      "Risk của dự án",
    ],
    doesNotHandle: ["Dữ liệu project ngoài phạm vi", "Quyết định cấp công ty"],
    dashboardLayers: ["project"],
    decisionVisibility: {
      approvalLevels: ["DEPARTMENT_HEAD", "PROJECT_DIRECTOR", "CEO", "CHAIRMAN"],
      riskLevels: ["medium", "high", "critical"],
      projectImportances: ["standard", "important", "strategic"],
      includeLegalImpact: true,
      includeScheduleImpact: true,
      includeTodayDecisions: true,
    },
  },
  {
    role: "DEPARTMENT_HEAD",
    label: "Department Head / Trưởng bộ phận",
    hierarchyLevel: 200,
    scope: "Theo bộ phận chuyên môn và project được phân quyền.",
    manages: [
      "Chuyên môn sâu",
      "Nhân sự bộ phận",
      "Hồ sơ chuyên môn",
      "Checklist",
      "Workflow",
      "Approval cấp bộ phận",
    ],
    doesNotHandle: ["Dashboard chiến lược toàn công ty", "Project ngoài quyền"],
    dashboardLayers: ["department"],
    decisionVisibility: {
      approvalLevels: ["DEPARTMENT_HEAD"],
      riskLevels: ["low", "medium", "high", "critical"],
      projectImportances: ["standard", "important", "strategic"],
      includeLegalImpact: true,
      includeScheduleImpact: true,
      includeTodayDecisions: true,
    },
  },
  {
    role: "STAFF",
    label: "Staff / Nhân sự",
    hierarchyLevel: 100,
    scope: "Chỉ việc được giao và module được phân quyền.",
    manages: [
      "Nhập dữ liệu",
      "Upload hồ sơ",
      "Báo cáo tiến độ",
      "Gửi trình duyệt",
      "Thực hiện task",
    ],
    doesNotHandle: ["Executive dashboard", "Dữ liệu tổng hợp lãnh đạo"],
    dashboardLayers: [],
    decisionVisibility: {
      approvalLevels: [],
      riskLevels: [],
      projectImportances: [],
      includeLegalImpact: false,
      includeScheduleImpact: false,
      includeTodayDecisions: false,
    },
  },
];

export const executiveAxisDefinitions: ExecutiveAxisDefinition[] = [
  {
    id: "project_management",
    label: "Dự án",
    englishLabel: "Project Management",
    description:
      "Trục 1 chỉ đưa lên Ban lãnh đạo các hồ sơ, rủi ro và quyết định dự án cần xem, duyệt hoặc phản hồi.",
    modules: [
      {
        id: "project-idea",
        label: "Ý tưởng dự án",
        executiveScope: "Chỉ trình khi cần quyết định mở hướng nghiên cứu.",
      },
      {
        id: "land-bank",
        label: "Quỹ đất",
        executiveScope: "Đưa lên khi liên quan chủ trương, pháp lý hoặc vượt ngưỡng.",
      },
      {
        id: "planning",
        label: "Quy hoạch",
        executiveScope: "Tổng hợp blocker quy hoạch và quyết định định hướng.",
      },
      {
        id: "social-housing-conditions",
        label: "Điều kiện NƠXH",
        executiveScope: "Theo dõi điều kiện ảnh hưởng khả năng triển khai.",
      },
      {
        id: "pre-feasibility",
        label: "Tiền khả thi",
        executiveScope: "Tóm tắt hiệu quả đầu tư và rủi ro lớn.",
      },
      {
        id: "investment-policy",
        label: "Chủ trương đầu tư",
        executiveScope: "Quyết định cấp cao trước khi mở hoặc chuyển giai đoạn.",
      },
      {
        id: "master-plan-1-500",
        label: "Quy hoạch 1/500",
        executiveScope: "Chỉ báo cáo vướng mắc hoặc thay đổi quan trọng.",
      },
      {
        id: "base-design",
        label: "Thiết kế cơ sở",
        executiveScope: "Chỉ trình thay đổi quan trọng hoặc ảnh hưởng tiến độ.",
      },
      {
        id: "feasibility-report",
        label: "Báo cáo khả thi",
        executiveScope: "Tóm tắt quyết định và điểm vượt ngưỡng.",
      },
      {
        id: "investor-approval",
        label: "Chấp thuận chủ đầu tư",
        executiveScope: "Theo dõi mốc pháp lý trọng yếu.",
      },
      {
        id: "land-allocation",
        label: "Giao đất",
        executiveScope: "Cảnh báo đỏ khi ảnh hưởng pháp lý, dòng tiền hoặc tiến độ.",
      },
    ],
    approvalCategories: [
      "legal_approval",
      "planning_approval",
      "design_approval",
      "feasibility_approval",
      "investment_approval",
    ],
    riskCategories: [
      "legal_risk",
      "land_risk",
      "planning_risk",
      "approval_risk",
      "schedule_risk",
    ],
  },
  {
    id: "build_management",
    label: "Kiến tạo",
    englishLabel: "Build Management",
    description:
      "Trục 2 chỉ đưa lên Ban lãnh đạo các cảnh báo thi công, nhà thầu, chất lượng, an toàn và thanh toán vượt ngưỡng.",
    modules: [
      { id: "construction-progress", label: "Tiến độ", executiveScope: "Mốc ảnh hưởng tổng tiến độ." },
      { id: "contractor", label: "Nhà thầu", executiveScope: "Chọn hoặc thay đổi nhà thầu quan trọng." },
      { id: "material", label: "Vật tư", executiveScope: "Vật tư ảnh hưởng chất lượng, chi phí hoặc tiến độ." },
      { id: "acceptance", label: "Nghiệm thu", executiveScope: "Nghiệm thu ảnh hưởng thanh toán hoặc bàn giao." },
      { id: "quality", label: "Chất lượng", executiveScope: "Rủi ro chất lượng HIGH/CRITICAL." },
      { id: "payment", label: "Thanh toán", executiveScope: "Thanh toán vượt ngưỡng hoặc ảnh hưởng dòng tiền." },
    ],
    approvalCategories: [
      "contractor_approval",
      "material_approval",
      "progress_approval",
      "variation_order_approval",
      "acceptance_approval",
      "payment_approval",
    ],
    riskCategories: [
      "delay_risk",
      "quality_risk",
      "safety_risk",
      "contractor_risk",
      "cost_overrun_risk",
      "material_risk",
    ],
  },
  {
    id: "operations_analytics",
    label: "Điều hành",
    englishLabel: "Operations & Analytics",
    description:
      "Trục 3 tổng hợp KPI, dòng tiền, audit, phân quyền và quyết định chiến lược.",
    modules: [
      { id: "kpi", label: "KPI", executiveScope: "KPI tổng và điểm lệch mục tiêu." },
      { id: "cashflow", label: "Dòng tiền", executiveScope: "Dòng tiền tổng và cảnh báo vượt ngưỡng." },
      { id: "audit", label: "Audit", executiveScope: "Audit rủi ro hoặc truy cập bị từ chối." },
      { id: "risk", label: "Risk", executiveScope: "Risk map điều hành." },
      { id: "permissions", label: "Phân quyền", executiveScope: "Thay đổi quyền nhạy cảm." },
      { id: "executive-reporting", label: "Báo cáo tổng", executiveScope: "Báo cáo tổng hợp cho lãnh đạo." },
    ],
    approvalCategories: [
      "budget_approval",
      "executive_payment_approval",
      "kpi_approval",
      "strategy_approval",
      "permission_approval",
    ],
    riskCategories: [
      "cashflow_risk",
      "operational_risk",
      "permission_risk",
      "compliance_risk",
      "system_risk",
    ],
  },
];

export const executiveScopeRules: ExecutiveScopeRule[] = [
  {
    id: "super-admin-all-organizations",
    description: "SUPER_ADMIN có thể kiểm tra toàn bộ organization/project.",
    roles: ["super_admin"],
    operatingRole: "CHAIRMAN",
    scopeType: "global",
    organizationIds: "all",
    projectIds: "all",
    axisIds: "all",
    moduleIds: "all",
    permission: "executive.global.view",
    canViewAllOrganizations: true,
    canViewAllProjects: true,
  },
  {
    id: "external-managed-project-director",
    description: "Giám đốc dự án organization ngoài chỉ thấy project được giao.",
    roles: ["giam_doc_du_an"],
    userIdIncludes: "horizon",
    operatingRole: "PROJECT_DIRECTOR",
    scopeType: "project",
    organizationIds: ["org-horizon"],
    projectIds: ["project-horizon-park"],
    axisIds: "all",
    moduleIds: "all",
    permission: "executive.external.project.view",
  },
  {
    id: "green-nest-project-director",
    description: "Giám đốc dự án Green Nest chỉ thấy dự án được giao.",
    roles: ["giam_doc_du_an"],
    operatingRole: "PROJECT_DIRECTOR",
    scopeType: "project",
    organizationIds: ["org-green-nest"],
    projectIds: ["project-riverside"],
    axisIds: "all",
    moduleIds: "all",
    permission: "executive.project.view",
  },
  {
    id: "axis-1-department-heads",
    description: "Trưởng bộ phận Trục 1 thấy project được cấp quyền theo chuyên môn.",
    roles: ["dau_tu_phat_trien", "phap_ly"],
    operatingRole: "DEPARTMENT_HEAD",
    scopeType: "department",
    organizationIds: ["org-green-nest"],
    projectIds: "by_organization",
    axisIds: ["project_management"],
    moduleIds: "all",
    permission: "executive.department.axis1.view",
    canViewAllProjects: true,
  },
  {
    id: "axis-2-department-heads",
    description: "Trưởng bộ phận Trục 2 thấy project được cấp quyền theo chuyên môn.",
    roles: [
      "thiet_ke",
      "ky_thuat",
      "thi_cong",
      "qa_qc_chat_luong",
      "an_toan_lao_dong",
    ],
    operatingRole: "DEPARTMENT_HEAD",
    scopeType: "department",
    organizationIds: ["org-green-nest"],
    projectIds: "by_organization",
    axisIds: ["build_management"],
    moduleIds: "all",
    permission: "executive.department.axis2.view",
    canViewAllProjects: true,
  },
  {
    id: "axis-3-department-heads",
    description: "Trưởng bộ phận Trục 3 thấy project được cấp quyền theo chuyên môn.",
    roles: ["quan_ly_tai_chinh", "quan_ly_hop_dong"],
    operatingRole: "DEPARTMENT_HEAD",
    scopeType: "department",
    organizationIds: ["org-green-nest"],
    projectIds: "by_organization",
    axisIds: ["operations_analytics"],
    moduleIds: "all",
    permission: "executive.department.axis3.view",
    canViewAllProjects: true,
  },
  {
    id: "assigned-portfolio-leader",
    description: "Lãnh đạo danh mục thấy nhiều dự án Green Nest được phân công.",
    roles: ["pho_tong_giam_doc"],
    operatingRole: "CEO",
    scopeType: "portfolio",
    organizationIds: ["org-green-nest"],
    projectIds: ["project-riverside", "project-city", "project-ocean"],
    axisIds: "all",
    moduleIds: "all",
    permission: "executive.portfolio.view",
  },
  {
    id: "green-nest-company-executive",
    description: "Chủ tịch/TGĐ/Company Admin thấy danh mục Green Nest theo quyền công ty.",
    roles: ["admin", "tong_giam_doc"],
    operatingRole: "CEO",
    scopeType: "global",
    organizationIds: ["org-green-nest"],
    projectIds: "by_organization",
    axisIds: "all",
    moduleIds: "all",
    permission: "executive.company.view",
    canViewAllProjects: true,
  },
];

// Fallback seed only. Active executive escalation rules are built from policy settings.
export const escalationRules: ExecutiveEscalationRule[] = [
  {
    id: "approval-under-20m",
    approvalLevel: "DEPARTMENT_HEAD",
    thresholdLabel: "Duoi 20 trieu",
    amountMax: 20_000_000,
    autoEscalationSignals: ["Tac vu chuyen mon thong thuong"],
  },
  {
    id: "approval-20m-200m",
    approvalLevel: "PROJECT_DIRECTOR",
    thresholdLabel: "20 trieu den 200 trieu",
    amountMin: 20_000_000,
    amountMax: 200_000_000,
    autoEscalationSignals: ["Chi phi trong ngan sach du an"],
  },
  {
    id: "approval-200m-2b",
    approvalLevel: "CEO",
    thresholdLabel: "200 trieu den 2 ty",
    amountMin: 200_000_000,
    amountMax: 2_000_000_000,
    autoEscalationSignals: [
      "Anh huong dong tien tong",
      "Thay doi tong muc dau tu",
    ],
  },
  {
    id: "approval-over-2b",
    approvalLevel: "CHAIRMAN",
    thresholdLabel: "Tren 2 ty hoac quyet dinh chien luoc",
    amountMin: 2_000_000_000,
    autoEscalationSignals: [
      "Rui ro phap ly HIGH/CRITICAL",
      "Thay doi nha thau chinh",
      "Lien quan quy dat/chu truong dau tu",
    ],
  },
];

export const dashboardLayers: ExecutiveDashboardLayer[] = [
  {
    id: "global-executive-dashboard",
    layer: "global",
    title: "Global Executive Dashboard",
    description:
      "Danh cho Chu tich/TGD: KPI tong, dong tien tong, rui ro do va quyet dinh cap cao.",
    targetRole: "CHAIRMAN",
    scopeLabel: "Toan cong ty / toan he sinh thai duoc cap quyen",
    kpis: [
      {
        id: "global-project-count",
        label: "Tong so du an",
        value: 24,
        helper: "12 xanh, 8 vang, 4 do",
        tone: "blue",
      },
      {
        id: "global-cashflow",
        label: "Dong tien tong",
        value: "186 ty",
        helper: "Ke hoach giai ngan 30 ngay",
        tone: "emerald",
      },
      {
        id: "global-high-approval",
        label: "Cho duyet cap cao",
        value: "31.5 ty",
        helper: "CEO/Chairman threshold",
        tone: "purple",
      },
      {
        id: "global-red-risk",
        label: "Du an canh bao do",
        value: 4,
        helper: "Phap ly, tien do, tai chinh",
        tone: "red",
      },
    ],
  },
  {
    id: "project-executive-dashboard",
    layer: "project",
    title: "Project Executive Dashboard",
    description:
      "Danh cho Giam doc du an: tinh trang du an, trinh duyet, chi phi phat sinh va rui ro trong pham vi duoc giao.",
    targetRole: "PROJECT_DIRECTOR",
    scopeLabel: "Mot hoac nhieu du an duoc giao",
    kpis: [
      {
        id: "project-progress",
        label: "Tien do du an",
        value: "65%",
        helper: "Riverside dang thi cong",
        tone: "blue",
      },
      {
        id: "project-late-docs",
        label: "Ho so cham",
        value: 6,
        helper: "Can xu ly trong tuan",
        tone: "amber",
      },
      {
        id: "project-cost-variance",
        label: "Chi phi phat sinh",
        value: "180 tr",
        helper: "Trong nguong GDDA",
        tone: "purple",
      },
      {
        id: "project-risk",
        label: "Rui ro du an",
        value: "High",
        helper: "Tien do bi anh huong",
        tone: "red",
      },
    ],
  },
  {
    id: "department-workspace-summary",
    layer: "department",
    title: "Department Workspace Summary",
    description:
      "Danh cho truong bo phan: cong viec chuyen mon, ho so can xu ly, viec qua han va nhan su phu trach.",
    targetRole: "DEPARTMENT_HEAD",
    scopeLabel: "Bo phan chuyen mon va cac project duoc cap quyen",
    kpis: [
      {
        id: "department-open-work",
        label: "Viec chuyen mon",
        value: 17,
        helper: "Dang mo trong bo phan",
        tone: "blue",
      },
      {
        id: "department-docs",
        label: "Ho so can xu ly",
        value: 9,
        helper: "Can phan hoi truoc deadline",
        tone: "amber",
      },
      {
        id: "department-overdue",
        label: "Qua han",
        value: 3,
        helper: "Can nhac nhan su phu trach",
        tone: "red",
      },
      {
        id: "department-review",
        label: "Trinh duyet can phan hoi",
        value: 5,
        helper: "Trong nguong truong bo phan",
        tone: "emerald",
      },
    ],
  },
];

export const globalStatusItems: ExecutiveGlobalStatusItem[] = [
  {
    id: "global-active-projects",
    kind: "active_projects",
    label: "Dự án active",
    value: 12,
    helper: "Realtime danh mục",
    tone: "emerald",
  },
  {
    id: "global-legal-blockers",
    kind: "legal_blockers",
    label: "Pháp lý blocker",
    value: 3,
    helper: "Cảnh báo",
    tone: "red",
  },
  {
    id: "global-pending-approvals",
    kind: "pending_approvals",
    label: "Phê duyệt chờ",
    value: 5,
    helper: "Queue lãnh đạo",
    tone: "purple",
  },
  {
    id: "global-today-meetings",
    kind: "today_meetings",
    label: "Họp hôm nay",
    value: 2,
    helper: "Operation",
    tone: "blue",
  },
  {
    id: "global-risk-level",
    kind: "risk_level",
    label: "Risk level",
    value: "Medium",
    helper: "AI theo dõi",
    tone: "amber",
  },
];

export const workspaceSwitchItems: ExecutiveWorkspaceSwitchItem[] = [
  {
    id: "workspace-executive",
    label: "Ban lãnh đạo",
    href: "/executive",
    group: "Trục 1",
  },
  {
    id: "workspace-development",
    label: "Phát triển dự án",
    href: "/axis-1",
    group: "Trục 1",
  },
  {
    id: "workspace-legal",
    label: "Pháp lý",
    href: "/legal",
    group: "Trục 1",
  },
  {
    id: "workspace-delivery",
    label: "Triển khai dự án",
    href: "/project-workbench",
    group: "Trục 2",
  },
  {
    id: "workspace-operations",
    label: "Quản trị - hỗ trợ",
    href: "/finance-management-workspace",
    group: "Trục 3",
  },
];

export const progressSegments: ExecutiveProgressSegment[] = [
  { label: "Hoàn thiện pháp lý", value: 5, percent: 21, color: "#22c55e" },
  { label: "Thiết kế", value: 4, percent: 17, color: "#3b82f6" },
  { label: "Thi công", value: 8, percent: 33, color: "#f59e0b" },
  { label: "Bàn giao", value: 4, percent: 17, color: "#8b5cf6" },
  { label: "Tạm dừng", value: 3, percent: 12, color: "#cbd5e1" },
];

export const overviewCards: ExecutiveOverviewCard[] = [
  {
    id: "overview-tracked-projects",
    key: "tracked_projects",
    label: "Tổng số dự án đang theo dõi",
    value: 24,
    helper: "12 dự án active, 8 chuẩn bị, 4 tạm dừng",
    tone: "blue",
  },
  {
    id: "overview-overdue-directives",
    key: "overdue_directives",
    label: "Việc/chỉ đạo quá hạn",
    value: 18,
    helper: "6 việc cần nhắc trong 24 giờ",
    tone: "red",
  },
  {
    id: "overview-legal-blockers",
    key: "legal_blockers",
    label: "Hồ sơ pháp lý đang vướng",
    value: 7,
    helper: "3 hồ sơ đang chặn mốc phê duyệt",
    tone: "amber",
  },
  {
    id: "overview-pending-proposals",
    key: "pending_proposals",
    label: "Đề xuất chờ duyệt",
    value: 11,
    helper: "5 đề xuất cần quyết định tuần này",
    tone: "purple",
  },
  {
    id: "overview-high-risks",
    key: "high_risks",
    label: "Rủi ro cao cần xử lý",
    value: 4,
    helper: "Pháp lý, ngân sách và tiến độ",
    tone: "red",
  },
];

export const commandCenterSnapshot: ExecutiveCommandCenterSnapshot = {
  notes: [
    {
      id: "exec-note-001",
      title: "Ưu tiên tháo gỡ pháp lý Riverside",
      description:
        "Chờ quyết định hướng xử lý hồ sơ môi trường để không trễ mốc phê duyệt tiếp theo.",
      projectName: "GreenNest Riverside",
      ownerName: "Hoàng Thanh",
      href: "/command-center?view=executive-dashboard",
      tone: "red",
    },
    {
      id: "exec-note-002",
      title: "Giữ nguyên nguyên tắc chỉ xem việc cần quyết định",
      description:
        "Các dashboard phòng ban không đưa vào Ban lãnh đạo nếu không cần xem, duyệt hoặc phản hồi.",
      href: "/command-center?view=executive-dashboard",
      tone: "slate",
    },
  ],
  meetings: [
    {
      id: "exec-meeting-001",
      title: "Họp giao ban danh mục 3 trục",
      description:
        "Chốt blocker, duyệt queue trình và phân công xử lý quá hạn.",
      timeLabel: "22/05/2026 14:00",
      href: "/command-center?view=executive-dashboard",
      tone: "blue",
    },
    {
      id: "exec-meeting-002",
      title: "Review ngân sách và xin chi tuần",
      description: "Duyệt các khoản chi ảnh hưởng mốc triển khai.",
      timeLabel: "23/05/2026 09:30",
      href: "/command-center?view=executive-dashboard",
      tone: "purple",
    },
  ],
  workCalendar: [
    {
      id: "exec-calendar-001",
      title: "Chốt pháp lý Riverside",
      description: "Hạn xử lý trong ngày để cập nhật chỉ đạo cho đội pháp lý.",
      timeLabel: "Hôm nay",
      projectName: "GreenNest Riverside",
      href: "/command-center?view=executive-dashboard",
      tone: "red",
    },
    {
      id: "exec-calendar-002",
      title: "Duyệt thiết kế cơ sở City",
      description: "Cần phản hồi trước khi nhóm thiết kế khóa hồ sơ tuần.",
      timeLabel: "24/05/2026",
      projectName: "GreenNest City",
      href: "/command-center?view=executive-dashboard",
      tone: "amber",
    },
  ],
  approvalQueue: [
    {
      id: "exec-approval-001",
      title: "Phê duyệt thiết kế cơ sở",
      description: "Đang chờ lãnh đạo duyệt để chuyển giai đoạn.",
      projectName: "GreenNest City",
      ownerName: "Quỳnh Ngân",
      href: "/command-center?view=executive-dashboard",
      tone: "purple",
    },
    {
      id: "exec-approval-002",
      title: "Xin chi khảo sát nhà thầu",
      description: "Khoản chi cần duyệt để giữ lịch khảo sát hiện trường.",
      projectName: "GreenNest Airport",
      ownerName: "Phúc Lâm",
      href: "/command-center?view=executive-dashboard",
      tone: "amber",
    },
  ],
  alerts: [
    {
      id: "exec-alert-001",
      title: "4 rủi ro cao cần quyết định",
      description:
        "Tập trung vào pháp lý, ngân sách, tiến độ thi công và giải phóng mặt bằng.",
      href: "/command-center?view=executive-dashboard",
      tone: "red",
    },
    {
      id: "exec-alert-002",
      title: "18 việc/chỉ đạo đã quá hạn",
      description:
        "6 việc cần nhắc trong 24 giờ để giảm rủi ro trễ dây chuyền.",
      href: "/command-center?view=executive-dashboard",
      tone: "amber",
    },
  ],
  quickReports: [
    {
      id: "exec-report-001",
      title: "Trình duyệt",
      value: 9,
      helper: "Hồ sơ đang chờ xem hoặc phản hồi",
      href: "/command-center?view=executive-dashboard",
      tone: "blue",
    },
    {
      id: "exec-report-002",
      title: "Xin chi",
      value: 4,
      helper: "Khoản chi cần quyết định",
      href: "/command-center?view=executive-dashboard",
      tone: "purple",
    },
    {
      id: "exec-report-003",
      title: "Quá hạn",
      value: 18,
      helper: "Việc/chỉ đạo cần nhắc xử lý",
      href: "/command-center?view=executive-dashboard",
      tone: "red",
    },
    {
      id: "exec-report-004",
      title: "Ảnh hưởng tiến độ",
      value: 5,
      helper: "Việc có nguy cơ kéo trễ mốc dự án",
      href: "/command-center?view=executive-dashboard",
      tone: "amber",
    },
    {
      id: "exec-report-005",
      title: "Quyết định trong ngày",
      value: 2,
      helper: "Việc cần chốt trước cuối ngày",
      href: "/command-center?view=executive-dashboard",
      tone: "red",
    },
  ],
};

export const urgentItems: ExecutiveUrgentItem[] = [
  {
    id: "urgent-001",
    projectId: "project-riverside",
    title: "Hoàn thiện hồ sơ môi trường dự án",
    projectName: "GreenNest Riverside",
    dueLabel: "2 ngày",
    ownerAvatarLabel: "HT",
    tone: "red",
  },
  {
    id: "urgent-002",
    projectId: "project-city",
    title: "Phê duyệt thiết kế cơ sở - Giai đoạn 1",
    projectName: "GreenNest City",
    dueLabel: "3 ngày",
    ownerAvatarLabel: "QN",
    tone: "red",
  },
  {
    id: "urgent-003",
    projectId: "project-ocean",
    title: "Báo cáo khảo sát địa chất",
    projectName: "GreenNest OceanView",
    dueLabel: "5 ngày",
    ownerAvatarLabel: "HY",
    tone: "amber",
  },
  {
    id: "urgent-004",
    projectId: "project-airport",
    title: "Hồ sơ PCCC - Giai đoạn 2",
    projectName: "GreenNest Airport",
    dueLabel: "7 ngày",
    ownerAvatarLabel: "PL",
    tone: "amber",
  },
  {
    id: "urgent-005",
    projectId: "project-long-an",
    title: "Cập nhật hồ sơ pháp lý đất đai",
    projectName: "GreenNest Long An",
    dueLabel: "9 ngày",
    ownerAvatarLabel: "LA",
    tone: "amber",
  },
];

export const leadershipActionItems: ExecutiveLeadershipActionItem[] = [
  {
    id: "leader-action-001",
    organizationId: "org-green-nest",
    organizationName: "Green Nest Group",
    projectId: "project-riverside",
    axis: "project_management",
    axisId: "project_management",
    moduleId: "legal",
    role: "CHAIRMAN",
    permission: "decision.approve",
    title: "Chốt hướng xử lý hồ sơ môi trường bổ sung",
    type: "legal",
    category: "overdue",
    projectName: "GreenNest Riverside",
    ownerName: "Hoàng Thanh",
    riskLevel: "critical",
    riskCategory: "legal_risk",
    approvalLevel: "CHAIRMAN",
    approvalType: "legal",
    approvalCategory: "legal_approval",
    projectImportance: "strategic",
    legalImpact: true,
    scheduleImpact: true,
    deadline: "2026-05-20",
    dueGroup: "overdue",
    priority: "critical",
    status: "overdue",
    decisionRequired:
      "Ra quyết định hướng bổ sung hồ sơ và người chịu trách nhiệm.",
    impactSummary:
      "Nếu chưa chốt trong ngày, mốc phê duyệt pháp lý tiếp theo có nguy cơ trễ thêm 1 tuần.",
    escalationReason:
      "Tự nâng cấp lên CHAIRMAN vì rủi ro pháp lý CRITICAL và liên quan mốc phê duyệt tổng thể.",
    scope: {
      organizationId: "org-green-nest",
      projectId: "project-riverside",
      axisId: "project_management",
      moduleId: "legal",
      role: "CHAIRMAN",
      permission: "decision.approve",
    },
    isScheduleImpact: true,
    requiresTodayDecision: true,
    href: "/command-center?view=executive-dashboard",
    tone: "red",
  },
  {
    id: "leader-action-002",
    organizationId: "org-green-nest",
    organizationName: "Green Nest Group",
    projectId: "project-city",
    axis: "project_management",
    axisId: "project_management",
    moduleId: "design",
    role: "CEO",
    permission: "proposal.approve",
    title: "Duyệt thiết kế cơ sở giai đoạn 1",
    type: "approval",
    category: "approval",
    projectName: "GreenNest City",
    ownerName: "Quỳnh Ngân",
    amount: 450_000_000,
    amountLabel: "450 triệu",
    riskLevel: "high",
    riskCategory: "schedule_risk",
    approvalLevel: "CEO",
    approvalType: "design",
    approvalCategory: "design_approval",
    projectImportance: "important",
    legalImpact: false,
    scheduleImpact: true,
    deadline: "2026-05-24",
    dueGroup: "this_week",
    priority: "high",
    status: "pending",
    decisionRequired: "Phê duyệt hoặc yêu cầu chỉnh sửa trước khi khóa hồ sơ.",
    impactSummary:
      "Quyết định trong tuần giúp đội thiết kế giữ lịch phát hành hồ sơ cơ sở.",
    escalationReason:
      "Tự nâng cấp lên CEO vì thay đổi thiết kế quan trọng và ảnh hưởng tiến độ hồ sơ cơ sở.",
    scope: {
      organizationId: "org-green-nest",
      projectId: "project-city",
      axisId: "project_management",
      moduleId: "design",
      role: "CEO",
      permission: "proposal.approve",
    },
    isScheduleImpact: true,
    requiresTodayDecision: false,
    href: "/command-center?view=executive-dashboard",
    tone: "purple",
  },
  {
    id: "leader-action-003",
    organizationId: "org-green-nest",
    organizationName: "Green Nest Group",
    projectId: "project-ocean",
    axis: "project_management",
    axisId: "project_management",
    moduleId: "land-clearance",
    role: "CHAIRMAN",
    permission: "decision.approve",
    title: "Xử lý rủi ro giải phóng mặt bằng khu B",
    type: "risk",
    category: "alert",
    projectName: "GreenNest OceanView",
    ownerName: "Hải Yến",
    riskLevel: "critical",
    riskCategory: "land_risk",
    approvalLevel: "CHAIRMAN",
    approvalType: "operation",
    approvalCategory: "investment_approval",
    projectImportance: "strategic",
    legalImpact: true,
    scheduleImpact: true,
    deadline: "2026-05-27",
    dueGroup: "this_week",
    priority: "critical",
    status: "high_risk",
    decisionRequired: "Chọn phương án xử lý để giữ lịch khảo sát địa chất.",
    impactSummary:
      "Rủi ro mặt bằng có thể kéo trễ khảo sát địa chất và mốc cập nhật tổng mức đầu tư.",
    escalationReason:
      "Tự nâng cấp lên CHAIRMAN vì liên quan quỹ đất, pháp lý và nguy cơ đổi tổng mức đầu tư.",
    scope: {
      organizationId: "org-green-nest",
      projectId: "project-ocean",
      axisId: "project_management",
      moduleId: "land-clearance",
      role: "CHAIRMAN",
      permission: "decision.approve",
    },
    isScheduleImpact: true,
    requiresTodayDecision: false,
    href: "/command-center?view=executive-dashboard",
    tone: "red",
  },
  {
    id: "leader-action-004",
    organizationId: "org-green-nest",
    organizationName: "Green Nest Group",
    projectId: "project-airport",
    axis: "operations_analytics",
    axisId: "operations_analytics",
    moduleId: "finance",
    role: "CEO",
    permission: "payment.approve",
    title: "Phản hồi đề xuất tăng ngân sách concept",
    type: "payment",
    category: "payment_request",
    projectName: "GreenNest Airport",
    ownerName: "Phúc Lâm",
    amount: 250_000_000,
    amountLabel: "250 triệu",
    riskLevel: "high",
    riskCategory: "cashflow_risk",
    approvalLevel: "CEO",
    approvalType: "finance",
    approvalCategory: "budget_approval",
    projectImportance: "important",
    legalImpact: false,
    scheduleImpact: false,
    deadline: "2026-05-28",
    dueGroup: "this_week",
    priority: "high",
    status: "pending",
    decisionRequired: "Duyệt xin chi có điều kiện hoặc yêu cầu giảm phạm vi.",
    impactSummary:
      "Khoản chi ảnh hưởng kế hoạch concept nhưng chưa chặn mốc vận hành trong ngày.",
    escalationReason:
      "Tự nâng cấp lên CEO vì vượt ngưỡng 200 triệu và ảnh hưởng ngân sách concept.",
    scope: {
      organizationId: "org-green-nest",
      projectId: "project-airport",
      axisId: "operations_analytics",
      moduleId: "finance",
      role: "CEO",
      permission: "payment.approve",
    },
    isScheduleImpact: false,
    requiresTodayDecision: false,
    href: "/command-center?view=executive-dashboard",
    tone: "amber",
  },
  {
    id: "leader-action-005",
    organizationId: "org-green-nest",
    organizationName: "Green Nest Group",
    projectId: "project-long-an",
    axis: "project_management",
    axisId: "project_management",
    moduleId: "legal",
    role: "PROJECT_DIRECTOR",
    permission: "decision.create",
    title: "Cập nhật chỉ đạo pháp lý đất đai sau cuộc họp tuần",
    type: "directive",
    category: "priority",
    projectName: "GreenNest Long An",
    ownerName: "Lan Anh",
    riskLevel: "medium",
    riskCategory: "land_risk",
    approvalLevel: "PROJECT_DIRECTOR",
    approvalType: "legal",
    approvalCategory: "legal_approval",
    projectImportance: "standard",
    legalImpact: true,
    scheduleImpact: true,
    deadline: "2026-05-29",
    dueGroup: "this_week",
    priority: "medium",
    status: "in_progress",
    decisionRequired: "Xác nhận nội dung chỉ đạo để gửi lại đội pháp lý.",
    impactSummary:
      "Chậm xác nhận sẽ làm đội pháp lý thiếu căn cứ cập nhật hồ sơ đất đai.",
    escalationReason:
      "Nằm trong phạm vi Giám đốc dự án vì cần chốt chỉ đạo dự án, chưa vượt ngưỡng CEO.",
    scope: {
      organizationId: "org-green-nest",
      projectId: "project-long-an",
      axisId: "project_management",
      moduleId: "legal",
      role: "PROJECT_DIRECTOR",
      permission: "decision.create",
    },
    isScheduleImpact: true,
    requiresTodayDecision: false,
    href: "/command-center?view=executive-dashboard",
    tone: "blue",
  },
  {
    id: "leader-action-006",
    organizationId: "org-green-nest",
    organizationName: "Green Nest Group",
    projectId: "project-riverside",
    axis: "build_management",
    axisId: "build_management",
    moduleId: "contractor",
    role: "PROJECT_DIRECTOR",
    permission: "contract.approve",
    title: "Duyệt phương án nhà thầu phụ kết cấu",
    type: "approval",
    category: "submission",
    projectName: "GreenNest Riverside",
    ownerName: "Minh Quân",
    amount: 180_000_000,
    amountLabel: "180 triệu",
    riskLevel: "high",
    riskCategory: "contractor_risk",
    approvalLevel: "PROJECT_DIRECTOR",
    approvalType: "operation",
    approvalCategory: "contractor_approval",
    projectImportance: "important",
    legalImpact: false,
    scheduleImpact: true,
    deadline: "2026-05-22",
    dueGroup: "today",
    priority: "high",
    status: "pending",
    decisionRequired: "Chọn phương án nhà thầu để không chậm mốc thi công.",
    impactSummary:
      "Cần quyết định trong ngày để tránh trượt lịch huy động nhà thầu phụ.",
    escalationReason:
      "Ngưỡng 20-200 triệu thuộc Giám đốc dự án, có gắn cờ ảnh hưởng tiến độ.",
    scope: {
      organizationId: "org-green-nest",
      projectId: "project-riverside",
      axisId: "build_management",
      moduleId: "contractor",
      role: "PROJECT_DIRECTOR",
      permission: "contract.approve",
    },
    isScheduleImpact: true,
    requiresTodayDecision: true,
    href: "/command-center?view=executive-dashboard",
    tone: "purple",
  },
  {
    id: "leader-action-007",
    organizationId: "org-green-nest",
    organizationName: "Green Nest Group",
    projectId: "project-city",
    axis: "build_management",
    axisId: "build_management",
    moduleId: "safety",
    role: "CEO",
    permission: "safety.approve",
    title: "Cảnh báo an toàn thi công tầng hầm",
    type: "risk",
    category: "alert",
    projectName: "GreenNest City",
    ownerName: "Bảo Khang",
    riskLevel: "critical",
    riskCategory: "safety_risk",
    approvalLevel: "CEO",
    approvalType: "operation",
    approvalCategory: "progress_approval",
    projectImportance: "important",
    legalImpact: false,
    scheduleImpact: true,
    deadline: "2026-05-23",
    dueGroup: "this_week",
    priority: "critical",
    status: "blocked",
    decisionRequired: "Xác nhận dừng/tiếp tục thi công sau biện pháp an toàn.",
    impactSummary:
      "Nếu tiếp tục vướng, hạng mục tầng hầm có thể chậm 3 ngày so với kế hoạch tuần.",
    escalationReason:
      "Tự nâng cấp lên CEO vì rủi ro CRITICAL và có thể ảnh hưởng tiến độ tổng thể.",
    scope: {
      organizationId: "org-green-nest",
      projectId: "project-city",
      axisId: "build_management",
      moduleId: "safety",
      role: "CEO",
      permission: "safety.approve",
    },
    isScheduleImpact: true,
    requiresTodayDecision: false,
    href: "/command-center?view=executive-dashboard",
    tone: "red",
  },
  {
    id: "leader-action-008",
    organizationId: "org-green-nest",
    organizationName: "Green Nest Group",
    projectId: "project-airport",
    axis: "operations_analytics",
    axisId: "operations_analytics",
    moduleId: "finance",
    role: "CEO",
    permission: "finance.approve",
    title: "Phê duyệt báo cáo dòng tiền tuần",
    type: "approval",
    category: "approval",
    projectName: "GreenNest Airport",
    ownerName: "Thu Hà",
    amount: 1_200_000_000,
    amountLabel: "1.2 tỷ",
    riskLevel: "medium",
    riskCategory: "cashflow_risk",
    approvalLevel: "CEO",
    approvalType: "finance",
    approvalCategory: "executive_payment_approval",
    projectImportance: "important",
    legalImpact: false,
    scheduleImpact: false,
    deadline: "2026-05-24",
    dueGroup: "this_week",
    priority: "medium",
    status: "pending",
    decisionRequired: "Xác nhận kế hoạch giải ngân theo mức ưu tiên mới.",
    impactSummary:
      "Chưa ảnh hưởng mốc thi công, nhưng cần quyết định để giữ kế hoạch dòng tiền.",
    escalationReason:
      "Ngưỡng 200 triệu đến 2 tỷ thuộc CEO và liên quan dòng tiền tổng.",
    scope: {
      organizationId: "org-green-nest",
      projectId: "project-airport",
      axisId: "operations_analytics",
      moduleId: "finance",
      role: "CEO",
      permission: "finance.approve",
    },
    isScheduleImpact: false,
    requiresTodayDecision: false,
    href: "/command-center?view=executive-dashboard",
    tone: "blue",
  },
  {
    id: "leader-action-009",
    organizationId: "org-green-nest",
    organizationName: "Green Nest Group",
    projectId: "project-ocean",
    axis: "operations_analytics",
    axisId: "operations_analytics",
    moduleId: "reporting",
    role: "CEO",
    permission: "proposal.approve",
    title: "Ưu tiên xử lý báo cáo pháp lý và ngân sách",
    type: "proposal",
    category: "priority",
    projectName: "GreenNest OceanView",
    ownerName: "Hải Yến",
    riskLevel: "high",
    riskCategory: "compliance_risk",
    approvalLevel: "CEO",
    approvalType: "operation",
    approvalCategory: "strategy_approval",
    projectImportance: "strategic",
    legalImpact: true,
    scheduleImpact: false,
    deadline: "2026-06-02",
    dueGroup: "later",
    priority: "high",
    status: "in_progress",
    decisionRequired: "Chọn thứ tự ưu tiên trước khi lập báo cáo HĐQT.",
    impactSummary:
      "Thứ tự ưu tiên quyết định nội dung báo cáo nhưng chưa chặn tiến độ hiện trường.",
    escalationReason:
      "Tự nâng cấp lên CEO vì rủi ro pháp lý HIGH và liên quan báo cáo HĐQT.",
    scope: {
      organizationId: "org-green-nest",
      projectId: "project-ocean",
      axisId: "operations_analytics",
      moduleId: "reporting",
      role: "CEO",
      permission: "proposal.approve",
    },
    isScheduleImpact: false,
    requiresTodayDecision: false,
    href: "/command-center?view=executive-dashboard",
    tone: "amber",
  },
  {
    id: "leader-action-010",
    organizationId: "org-horizon",
    organizationName: "Horizon Urban Partner",
    projectId: "project-horizon-park",
    axis: "project_management",
    axisId: "project_management",
    moduleId: "external-legal",
    role: "CHAIRMAN",
    permission: "decision.approve",
    title: "Quyết định chủ trương pháp lý Horizon Park",
    type: "legal",
    category: "alert",
    projectName: "Horizon Park Managed Project",
    ownerName: "Đội quản lý thuê",
    amount: 2_500_000_000,
    amountLabel: "2.5 tỷ",
    riskLevel: "critical",
    riskCategory: "approval_risk",
    approvalLevel: "CHAIRMAN",
    approvalType: "investment",
    approvalCategory: "investment_approval",
    projectImportance: "strategic",
    legalImpact: true,
    scheduleImpact: true,
    deadline: "2026-05-30",
    dueGroup: "this_week",
    priority: "critical",
    status: "high_risk",
    decisionRequired:
      "Chốt hướng pháp lý cấp chủ trương cho dự án quản lý thuê.",
    impactSummary:
      "Dữ liệu thuộc organization ngoài và chỉ hiển thị cho người được cấp quyền.",
    escalationReason:
      "Trên 2 tỷ và liên quan chủ trương đầu tư nên thuộc CHAIRMAN.",
    scope: {
      organizationId: "org-horizon",
      projectId: "project-horizon-park",
      axisId: "project_management",
      moduleId: "external-legal",
      role: "CHAIRMAN",
      permission: "decision.approve",
    },
    isScheduleImpact: true,
    requiresTodayDecision: false,
    href: "/command-center?view=executive-dashboard",
    tone: "red",
  },
  {
    id: "leader-action-011",
    organizationId: "org-green-nest",
    organizationName: "Green Nest Group",
    projectId: "project-long-an",
    axis: "project_management",
    axisId: "project_management",
    moduleId: "planning",
    role: "DEPARTMENT_HEAD",
    permission: "planning.review",
    title: "Rà soát checklist quy hoạch nội bộ Long An",
    type: "approval",
    category: "submission",
    projectName: "GreenNest Long An",
    ownerName: "Tổ quy hoạch",
    amount: 12_000_000,
    amountLabel: "12 triệu",
    riskLevel: "low",
    riskCategory: "planning_risk",
    approvalLevel: "DEPARTMENT_HEAD",
    approvalType: "operation",
    approvalCategory: "planning_approval",
    projectImportance: "standard",
    legalImpact: false,
    scheduleImpact: false,
    deadline: "2026-05-31",
    dueGroup: "this_week",
    priority: "low",
    status: "pending",
    decisionRequired:
      "Trưởng bộ phận xác nhận checklist trước khi nhóm dự án tự hoàn thiện.",
    impactSummary:
      "Đây là việc chuyên môn cấp bộ phận, không đưa mặc định lên Chủ tịch.",
    escalationReason:
      "Dưới 20 triệu, risk LOW và không ảnh hưởng tiến độ tổng thể nên thuộc DEPARTMENT_HEAD.",
    scope: {
      organizationId: "org-green-nest",
      projectId: "project-long-an",
      axisId: "project_management",
      moduleId: "planning",
      role: "DEPARTMENT_HEAD",
      permission: "planning.review",
    },
    isScheduleImpact: false,
    requiresTodayDecision: false,
    href: "/command-center?view=executive-dashboard",
    tone: "slate",
  },
];

export const projects: ExecutiveProjectRow[] = [
  {
    id: "project-riverside",
    projectId: "project-riverside",
    organizationId: "org-green-nest",
    organizationName: "Green Nest Group",
    name: "GreenNest Riverside",
    phase: "Thi công",
    progress: 65,
    investor: "GreenNest Group",
    health: "red",
    cashFlowLabel: "Can bo sung 12 ty trong 30 ngay",
    strategicImportance: "strategic",
    updatedAt: "27/05/2026",
    tone: "blue",
  },
  {
    id: "project-city",
    projectId: "project-city",
    organizationId: "org-green-nest",
    organizationName: "Green Nest Group",
    name: "GreenNest City",
    phase: "Thiết kế",
    progress: 40,
    investor: "GreenNest Group",
    health: "yellow",
    cashFlowLabel: "Dung ke hoach giai ngan",
    strategicImportance: "important",
    updatedAt: "27/05/2026",
    tone: "emerald",
  },
  {
    id: "project-ocean",
    projectId: "project-ocean",
    organizationId: "org-green-nest",
    organizationName: "Green Nest Group",
    name: "GreenNest OceanView",
    phase: "Thi công",
    progress: 75,
    investor: "GreenNest Group",
    health: "red",
    cashFlowLabel: "Can kiem soat phat sinh GPMB",
    strategicImportance: "strategic",
    updatedAt: "26/05/2026",
    tone: "amber",
  },
  {
    id: "project-airport",
    projectId: "project-airport",
    organizationId: "org-green-nest",
    organizationName: "Green Nest Group",
    name: "GreenNest Airport",
    phase: "Pháp lý",
    progress: 20,
    investor: "GreenNest Group",
    health: "yellow",
    cashFlowLabel: "Dang cho phe duyet ngan sach concept",
    strategicImportance: "important",
    updatedAt: "26/05/2026",
    tone: "purple",
  },
  {
    id: "project-long-an",
    projectId: "project-long-an",
    organizationId: "org-green-nest",
    organizationName: "Green Nest Group",
    name: "GreenNest Long An",
    phase: "Thiết kế",
    progress: 55,
    investor: "GreenNest Group",
    health: "green",
    cashFlowLabel: "Trong han muc phe duyet",
    strategicImportance: "standard",
    updatedAt: "25/05/2026",
    tone: "blue",
  },
  {
    id: "project-horizon-park",
    projectId: "project-horizon-park",
    organizationId: "org-horizon",
    organizationName: "Horizon Urban Partner",
    name: "Horizon Park Managed Project",
    phase: "Pháp lý",
    progress: 18,
    investor: "Horizon Urban Partner",
    health: "yellow",
    cashFlowLabel: "Du lieu tach biet theo organization ngoai",
    strategicImportance: "important",
    updatedAt: "25/05/2026",
    tone: "amber",
  },
];

export const schedule: ExecutiveScheduleItem[] = [
  {
    id: "schedule-1",
    projectId: "project-city",
    time: "08:30",
    title: "Họp đánh giá tiến độ dự án GreenNest City",
    location: "Phòng họp A - Tầng 5",
    tone: "emerald",
  },
  {
    id: "schedule-2",
    projectId: "project-city",
    time: "10:00",
    title: "Phê duyệt hồ sơ thiết kế cơ sở",
    location: "Online",
    tone: "amber",
  },
  {
    id: "schedule-3",
    time: "14:00",
    title: "Họp với đối tác Nhật Bản",
    location: "Phòng họp B - Tầng 3",
    tone: "blue",
  },
  {
    id: "schedule-4",
    time: "16:00",
    title: "Giao ban Ban lãnh đạo",
    location: "Phòng họp A - Tầng 5",
    tone: "purple",
  },
];

export const quickActions: ExecutiveQuickAction[] = [
  {
    label: "Tạo kế hoạch đầu tư",
    href: "/executive/investment-plans",
    tone: "emerald",
  },
  {
    label: "Tạo chỉ đạo điều hành",
    href: "/executive/directives",
    tone: "purple",
  },
  {
    label: "Tạo cuộc họp lãnh đạo",
    href: "/executive/meetings",
    tone: "amber",
  },
  {
    label: "Mở phê duyệt chờ xử lý",
    href: "/executive/approvals",
    tone: "blue",
  },
  {
    label: "Xem nhật ký quyết định",
    href: "/executive/decision-log",
    tone: "slate",
  },
];

export const notifications: ExecutiveNotification[] = [
  {
    id: "noti-1",
    projectId: "project-riverside",
    title: "Hồ sơ dự án Riverside bị trả về để bổ sung",
    time: "10:15",
    tone: "amber",
  },
  {
    id: "noti-2",
    title: "Yêu cầu phê duyệt ngân sách Marketing Q2/2026",
    time: "09:30",
    tone: "red",
  },
  {
    id: "noti-3",
    title: "Lịch họp giao ban Ban lãnh đạo hôm nay lúc 16:00",
    time: "08:45",
    tone: "blue",
  },
  {
    id: "noti-4",
    title: "Nguyễn Hoàng Nam vừa cập nhật tiến độ công việc",
    time: "08:15",
    tone: "slate",
  },
];

export const strategicPlans: StrategicInvestmentPlan[] = [
  {
    id: "plan-2026-south",
    title: "Kế hoạch đầu tư chiến lược 2026 - khu Nam",
    year: 2026,
    quarter: "Q2",
    targetArea: "TP.HCM mở rộng, Long An, Bình Dương",
    projectType: "Nhà ở thấp tầng",
    budgetRange: "1.200 tỷ",
    priority: "strategic",
    period: "Q2-Q4/2026",
    regionFocus: "TP.HCM mở rộng, Long An, Bình Dương",
    segmentFocus: "Nhà ở thấp tầng và chung cư trung tầng",
    budgetLabel: "1.200 tỷ",
    allocatedBudget: 1200,
    committedBudget: 760,
    status: "reviewing",
    createdBy: "ceo-01",
    createdAt: "2026-01-05T08:00:00+07:00",
    ownerName: "Đặng Quốc Bảo",
    updatedAt: "2026-05-20",
    priorities: [
      "Ưu tiên quỹ đất sạch",
      "IRR mục tiêu >= 18%",
      "Không mở dự án nếu pháp lý đất chưa rõ",
    ],
    targetAreas: ["Long An", "Bình Dương", "TP.HCM mở rộng"],
    projectTypes: ["Nhà ở thấp tầng", "Chung cư trung tầng"],
  },
  {
    id: "plan-2026-east",
    title: "Định hướng danh mục đô thị vệ tinh phía Đông",
    year: 2026,
    quarter: "FY",
    targetArea: "Đồng Nai, TP. Thủ Đức, Bà Rịa - Vũng Tàu",
    projectType: "Khu dân cư",
    budgetRange: "850 tỷ",
    priority: "high",
    period: "2026",
    regionFocus: "Đồng Nai, TP. Thủ Đức, Bà Rịa - Vũng Tàu",
    segmentFocus: "Khu dân cư quy mô vừa",
    budgetLabel: "850 tỷ",
    allocatedBudget: 850,
    committedBudget: 410,
    status: "approved",
    createdBy: "executive-01",
    createdAt: "2026-01-10T08:00:00+07:00",
    ownerName: "Trần Hoàng Nam",
    updatedAt: "2026-05-18",
    priorities: [
      "Tập trung dự án có kết nối hạ tầng",
      "Giới hạn M&A dưới 40% ngân sách",
      "Có kế hoạch pháp lý 6 tháng",
    ],
    targetAreas: ["Đồng Nai", "TP. Thủ Đức", "Bà Rịa - Vũng Tàu"],
    projectTypes: ["Khu dân cư", "Đô thị vệ tinh"],
  },
];

export const leadershipTeam: ExecutiveLeader[] = [
  {
    id: "ceo-01",
    fullName: "Đặng Quốc Bảo",
    position: "Tổng giám đốc",
    role: "tong_giam_doc",
    email: "ceo@greennest.vn",
    phone: "0832056565",
    approvalLevel: "final",
    isActive: true,
    title: "Tổng giám đốc",
    scope: "Toàn danh mục đầu tư và phê duyệt cấp công ty",
    authoritySummary:
      "Phê duyệt chủ trương nội bộ, ngân sách chiến lược, đề xuất rủi ro cao",
    permissions: [
      "Xem toàn bộ",
      "Phê duyệt",
      "Từ chối",
      "Yêu cầu sửa",
      "Ban hành chỉ đạo",
    ],
    status: "active",
  },
  {
    id: "executive-01",
    fullName: "Trần Hoàng Nam",
    position: "Phó tổng giám đốc",
    role: "pho_tong_giam_doc",
    email: "pho.tgd@greennest.vn",
    phone: "0832056565",
    approvalLevel: "company",
    isActive: true,
    title: "Phó tổng giám đốc",
    scope: "Danh mục khu Đông và các đề xuất được phân quyền",
    authoritySummary:
      "Review, yêu cầu chỉnh sửa, duyệt trong hạn mức được ủy quyền",
    permissions: [
      "Xem danh mục",
      "Phê duyệt trong hạn mức",
      "Yêu cầu sửa",
      "Ban hành chỉ đạo",
    ],
    status: "active",
  },
  {
    id: "investment-director-01",
    fullName: "Lâm Minh Đức",
    position: "Giám đốc đầu tư",
    role: "dau_tu_phat_trien",
    email: "investment@greennest.vn",
    phone: "0832056565",
    approvalLevel: "review",
    isActive: true,
    title: "Giám đốc đầu tư",
    scope: "Pipeline cơ hội đầu tư, tiền khả thi và hồ sơ trình chủ trương",
    authoritySummary: "Đề xuất, giải trình, chuẩn bị hồ sơ trình Ban lãnh đạo",
    permissions: [
      "Xem pipeline",
      "Tạo đề xuất",
      "Cập nhật hồ sơ",
      "Giải trình",
    ],
    status: "active",
  },
  {
    id: "assistant-01",
    fullName: "Trịnh Mai Anh",
    position: "Thư ký/Trợ lý lãnh đạo",
    role: "thu_ky_tro_ly",
    email: "assistant@greennest.vn",
    phone: "0832056565",
    approvalLevel: "none",
    isActive: true,
    title: "Thư ký/Trợ lý lãnh đạo",
    scope: "Chuẩn bị họp, biên bản, hồ sơ trình và nhật ký quyết định",
    authoritySummary:
      "Không phê duyệt; hỗ trợ tạo hồ sơ, meeting note và báo cáo nháp",
    permissions: [
      "Xem hồ sơ",
      "Tạo biên bản",
      "Theo dõi deadline",
      "Cập nhật nhật ký",
    ],
    status: "delegated",
  },
];

export const authorityMatrix: AuthorityMatrixRow[] = [
  {
    id: "authority-investment-principle",
    decisionArea: "Phê duyệt chủ trương nội bộ dự án mới",
    threshold: "Mọi dự án trước khi mở mã dự án chính thức",
    tongGiamDoc: "Phê duyệt cuối",
    phoTongGiamDoc: "Review và đề xuất trong phạm vi được giao",
    secretarySupport: "Chuẩn bị tờ trình, biên bản và nhật ký quyết định",
  },
  {
    id: "authority-budget",
    decisionArea: "Ngân sách đầu tư chiến lược",
    threshold: "Từ 100 tỷ trở lên hoặc vượt kế hoạch năm",
    tongGiamDoc: "Phê duyệt",
    phoTongGiamDoc: "Đồng review, yêu cầu bổ sung hiệu quả đầu tư",
    secretarySupport: "Tổng hợp hồ sơ, theo dõi phiên bản",
  },
  {
    id: "authority-risk",
    decisionArea: "Đề xuất có rủi ro pháp lý/quy hoạch cao",
    threshold: "Có blocker pháp lý, quy hoạch hoặc yêu cầu cơ quan",
    tongGiamDoc: "Phê duyệt hoặc từ chối",
    phoTongGiamDoc: "Yêu cầu chỉnh sửa, đề xuất điều kiện phê duyệt",
    secretarySupport: "Gắn hồ sơ, cuộc họp, công văn liên quan",
  },
];

export const directives: ExecutiveDirective[] = [
  {
    id: "directive-001",
    projectId: "project-riverside",
    title: "Hoàn thiện điều kiện pháp lý trước khi trình chủ trương nội bộ",
    content:
      "Hoàn thiện hồ sơ đất, căn cứ pháp lý và điều kiện trình chủ trương nội bộ.",
    assignedTo: "legal-manager",
    createdBy: "ceo-01",
    createdAt: "2026-05-20T10:00:00+07:00",
    projectName: "GreenNest Riverside",
    ownerName: "Phạm Thu Hà",
    receiverName: "Bộ phận pháp lý",
    dueDate: "2026-05-27",
    status: "in_progress",
    priority: "urgent",
    taskCode: "TASK-LD-001",
  },
  {
    id: "directive-002",
    projectId: "project-city",
    title: "Rà lại hiệu quả đầu tư theo kịch bản lãi suất mới",
    content:
      "Cập nhật mô hình hiệu quả đầu tư theo kịch bản lãi suất và nguồn vốn mới.",
    assignedTo: "finance-manager-01",
    createdBy: "executive-01",
    createdAt: "2026-05-19T09:30:00+07:00",
    projectName: "GreenNest City",
    ownerName: "Đinh Tài Chính",
    receiverName: "Tài chính - Đầu tư",
    dueDate: "2026-05-30",
    status: "open",
    priority: "high",
    taskCode: "TASK-LD-002",
  },
  {
    id: "directive-003",
    projectId: "project-airport",
    title: "Chốt phương án concept trước phiên họp lãnh đạo tuần tới",
    content:
      "Chốt phạm vi concept và các điểm cần lãnh đạo quyết định trước phiên họp tuần tới.",
    assignedTo: "designer",
    createdBy: "ceo-01",
    createdAt: "2026-05-18T16:00:00+07:00",
    projectName: "GreenNest Airport",
    ownerName: "Đỗ Hải Yến",
    receiverName: "Thiết kế - Quy hoạch",
    dueDate: "2026-05-24",
    status: "blocked",
    priority: "high",
    taskCode: "TASK-LD-003",
  },
];

export const meetings: LeadershipMeeting[] = [
  {
    id: "meeting-001",
    projectId: "project-riverside",
    title: "Họp lãnh đạo danh mục đầu tư tuần 22",
    meetingDate: "2026-05-27T16:00:00+07:00",
    participants: [
      "ceo-01",
      "executive-01",
      "investment-director-01",
      "assistant-01",
    ],
    agenda: [
      "Đề xuất Riverside Garden",
      "Ngân sách Q3",
      "Rủi ro pháp lý đang chờ cơ quan",
    ],
    opinions: [
      "TGĐ yêu cầu bổ sung căn cứ pháp lý đất",
      "PTGĐ đề xuất đưa rủi ro vào điều kiện phê duyệt",
    ],
    conclusion:
      "Chưa duyệt mở mã dự án; yêu cầu hoàn thiện pháp lý và dòng tiền trước phiên họp sau.",
    summary:
      "Cuộc họp tập trung vào đề xuất Riverside Garden, ngân sách Q3 và các rủi ro pháp lý đang chờ xử lý.",
    aiSummary:
      "AI mock cảnh báo hồ sơ pháp lý Riverside cần được ưu tiên trước khi quyết định mở mã dự án.",
    actionItems: [
      "Pháp lý bổ sung hồ sơ đất",
      "Đầu tư cập nhật dòng tiền",
      "Trợ lý phát hành biên bản",
    ],
    status: "scheduled",
    decisionCount: 3,
  },
  {
    id: "meeting-002",
    title: "Review chiến lược khu Đông",
    meetingDate: "2026-05-18T14:00:00+07:00",
    participants: ["executive-01", "investment-director-01", "assistant-01"],
    agenda: [
      "Danh sách cơ hội M&A",
      "Khả năng hấp thụ thị trường",
      "Điều kiện phê duyệt giai đoạn 1",
    ],
    opinions: [
      "Ưu tiên cơ hội có pháp lý đất sạch",
      "Không vượt trần M&A 40% kế hoạch năm",
    ],
    conclusion:
      "Tiếp tục nghiên cứu 3 cơ hội, dừng 1 cơ hội do rủi ro quy hoạch.",
    summary:
      "Review chiến lược khu Đông chốt nguyên tắc ưu tiên pháp lý đất sạch và kiểm soát tỷ trọng M&A.",
    aiSummary:
      "AI mock đề xuất giữ giới hạn M&A để bảo vệ dòng tiền và yêu cầu cập nhật shortlist cơ hội.",
    actionItems: [
      "Cập nhật shortlist",
      "Lập bảng rủi ro",
      "Chuẩn bị đề xuất nội bộ",
    ],
    status: "completed",
    decisionCount: 4,
  },
];

export const approvals: LeadershipApproval[] = [
  {
    id: "approval-001",
    projectId: "project-riverside",
    title: "Đề xuất nghiên cứu quỹ đất Riverside Garden",
    type: "investment",
    requestedBy: "investment-director-01",
    amount: 320_000_000_000,
    reason:
      "Cần lãnh đạo xem xét chủ trương nghiên cứu quỹ đất Riverside Garden.",
    attachments: ["ToTrinh_Riverside_v3.pdf"],
    status: "pending",
    approverId: "ceo-01",
    proposalCode: "DX-INVESTMENT-MOCK01",
    requester: "Lâm Minh Đức",
    amountLabel: "320 tỷ",
    dueDate: "2026-05-23",
    riskLevel: "high",
    attachmentLabel: "ToTrinh_Riverside_v3.pdf",
    version: "v3",
  },
  {
    id: "approval-002",
    projectId: "project-city",
    title: "Điều chỉnh ngân sách khảo sát Green Valley",
    type: "finance",
    requestedBy: "finance-manager-01",
    amount: 12_000_000_000,
    reason: "Cần bổ sung kịch bản chi phí khảo sát và nguồn vốn.",
    attachments: ["Budget_GreenValley_v2.xlsx"],
    status: "revision_required",
    approverId: "executive-01",
    decisionReason: "Cần bổ sung kịch bản chi phí khảo sát và nguồn vốn.",
    proposalCode: "DX-FINANCE-MOCK02",
    requester: "Đinh Tài Chính",
    amountLabel: "12 tỷ",
    dueDate: "2026-05-25",
    riskLevel: "medium",
    attachmentLabel: "Budget_GreenValley_v2.xlsx",
    version: "v2",
  },
  {
    id: "approval-003",
    projectId: "project-airport",
    title: "Chủ trương nội bộ concept East Link Residence",
    type: "design",
    requestedBy: "designer",
    reason: "Duyệt concept để tiếp tục thiết kế cơ sở.",
    attachments: ["Concept_EastLink_v1.pdf"],
    status: "approved",
    approverId: "ceo-01",
    decisionReason: "Duyệt concept để tiếp tục thiết kế cơ sở.",
    decidedAt: "2026-05-21T08:45:00+07:00",
    proposalCode: "DX-DESIGN-MOCK03",
    requester: "Đỗ Hải Yến",
    dueDate: "2026-05-29",
    riskLevel: "low",
    attachmentLabel: "Concept_EastLink_v1.pdf",
    version: "v1",
  },
];

export const decisionLog: ExecutiveDecisionLogItem[] = [
  {
    id: "decision-001",
    entityType: "approval",
    entityId: "approval-001",
    decision:
      "Chưa mở mã dự án Riverside Garden cho đến khi pháp lý đất hoàn tất bước bổ sung.",
    projectId: "project-riverside",
    decisionText:
      "Chưa mở mã dự án Riverside Garden cho đến khi pháp lý đất hoàn tất bước bổ sung.",
    decidedBy: "Đặng Quốc Bảo",
    decidedAt: "2026-05-20",
    source: "Họp lãnh đạo danh mục đầu tư",
    reason: "Pháp lý đất chưa đủ căn cứ để chuyển giai đoạn.",
    aiRecommendation:
      "AI mock khuyến nghị yêu cầu hoàn thiện pháp lý đất trước khi mở mã dự án.",
    version: "v1",
    status: "follow_up",
  },
  {
    id: "decision-002",
    entityType: "investment_plan",
    entityId: "plan-2026-east",
    decision: "Giữ trần ngân sách M&A khu Đông ở mức 40% kế hoạch năm 2026.",
    decisionText:
      "Giữ trần ngân sách M&A khu Đông ở mức 40% kế hoạch năm 2026.",
    decidedBy: "Trần Hoàng Nam",
    decidedAt: "2026-05-18",
    source: "Review chiến lược khu Đông",
    reason: "Kiểm soát rủi ro danh mục và dòng tiền.",
    version: "v2",
    status: "effective",
  },
  {
    id: "decision-003",
    entityType: "directive",
    entityId: "directive-002",
    decision:
      "Mọi đề xuất đầu tư mới phải có bảng kịch bản dòng tiền trước khi trình duyệt.",
    decisionText:
      "Mọi đề xuất đầu tư mới phải có bảng kịch bản dòng tiền trước khi trình duyệt.",
    decidedBy: "Đặng Quốc Bảo",
    decidedAt: "2026-05-15",
    source: "Chỉ đạo điều hành",
    reason: "Chuẩn hóa điều kiện ra quyết định đầu tư.",
    version: "v1",
    status: "effective",
  },
];

export const auditLog: ExecutiveAuditLogItem[] = [
  {
    id: "audit-decision-001",
    action: "decision.follow_up_created",
    entityType: "decision",
    entityId: "decision-001",
    projectId: "project-riverside",
    actorId: "ceo-01",
    actorName: "Đặng Quốc Bảo",
    createdAt: "2026-05-20T09:30:00+07:00",
    reason: "Pháp lý đất chưa đủ căn cứ để chuyển giai đoạn.",
    afterStatus: "follow_up",
  },
  {
    id: "audit-decision-002",
    action: "decision.effective_created",
    entityType: "decision",
    entityId: "decision-002",
    actorId: "executive-01",
    actorName: "Trần Hoàng Nam",
    createdAt: "2026-05-18T15:20:00+07:00",
    reason: "Kiểm soát rủi ro danh mục và dòng tiền.",
    afterStatus: "effective",
  },
  {
    id: "audit-directive-001",
    action: "directive.created",
    entityType: "directive",
    entityId: "directive-001",
    projectId: "project-riverside",
    actorId: "ceo-01",
    actorName: "Đặng Quốc Bảo",
    createdAt: "2026-05-20T10:00:00+07:00",
    reason:
      "Yêu cầu pháp lý bổ sung hồ sơ đất trước khi trình chủ trương nội bộ.",
    afterStatus: "in_progress",
  },
  {
    id: "audit-approval-003",
    action: "approval.approved",
    entityType: "approval",
    entityId: "approval-003",
    projectId: "project-airport",
    actorId: "ceo-01",
    actorName: "Đặng Quốc Bảo",
    createdAt: "2026-05-21T08:45:00+07:00",
    reason: "Duyệt concept để tiếp tục thiết kế cơ sở.",
    beforeStatus: "pending",
    afterStatus: "approved",
  },
];

export const aiInsights: ExecutiveAiInsight[] = [
  {
    id: "ai-001",
    projectId: "project-riverside",
    title: "Ưu tiên xử lý Riverside Garden",
    summary:
      "Đề xuất có ngân sách lớn, rủi ro pháp lý cao và đang chờ quyết định cấp lãnh đạo.",
    recommendedAction:
      "Yêu cầu chỉnh sửa hồ sơ pháp lý trước khi phê duyệt chủ trương nội bộ.",
    tone: "red",
  },
  {
    id: "ai-002",
    title: "Ngân sách khu Đông còn dư địa",
    summary:
      "Cam kết hiện tại thấp hơn 50% ngân sách phân bổ, nhưng cần khóa điều kiện IRR và pháp lý đất sạch.",
    recommendedAction:
      "Cho phép tiếp tục nghiên cứu, chưa mở mã dự án chính thức.",
    tone: "amber",
  },
  {
    id: "ai-003",
    projectId: "project-airport",
    title: "Chỉ đạo concept có nguy cơ trễ",
    summary:
      "GreenNest Airport bị chặn ở phương án concept trước cuộc họp tuần tới.",
    recommendedAction:
      "Giao PTGĐ chốt phạm vi review với Thiết kế trong 24 giờ.",
    tone: "purple",
  },
];

export const aiLeadershipSummary: ExecutiveAiLeadershipSummary = {
  attentionPoints: [
    {
      id: "ai-attention-001",
      projectId: "project-riverside",
      title: "Riverside cần quyết định hồ sơ môi trường",
      detail:
        "Hồ sơ bổ sung đã quá hạn 2 ngày và đang chặn mốc phê duyệt pháp lý tiếp theo.",
      tone: "red",
    },
    {
      id: "ai-attention-002",
      projectId: "project-city",
      title: "GreenNest City có đề xuất thiết kế chờ duyệt",
      detail:
        "Nếu duyệt trong tuần này, đội thiết kế vẫn giữ được lịch phát hành hồ sơ cơ sở.",
      tone: "purple",
    },
  ],
  risks: [
    {
      id: "ai-risk-001",
      projectId: "project-ocean",
      title: "Rủi ro giải phóng mặt bằng khu B",
      detail:
        "Khả năng trễ mốc khảo sát địa chất nếu chưa thống nhất phương án xử lý trong tuần.",
      tone: "red",
    },
    {
      id: "ai-risk-002",
      projectId: "project-airport",
      title: "Ngân sách concept có nguy cơ vượt ngưỡng",
      detail:
        "Đề xuất tăng ngân sách cần kèm phương án kiểm soát phạm vi trước khi phê duyệt.",
      tone: "amber",
    },
  ],
  weeklyPriorities: [
    {
      id: "ai-priority-001",
      projectId: "project-riverside",
      title: "Ưu tiên 1: chốt blocker pháp lý Riverside",
      detail:
        "Giao đầu mối pháp lý cập nhật hồ sơ và báo cáo quyết định trước cuộc họp thứ Sáu.",
      tone: "red",
    },
    {
      id: "ai-priority-002",
      projectId: "project-city",
      title: "Ưu tiên 2: dọn hàng chờ phê duyệt",
      detail:
        "Xử lý các đề xuất đã đủ điều kiện để giảm tải queue điều hành trong tuần.",
      tone: "emerald",
    },
  ],
};
